### ISSUE TITLE
[Discussion] Clean shutdown of streams and sockets

### ISSUE THREAD

**Issue by FanDjango** [robinrodricks/FluentFTP#1001]
@vasyaxparfenov
In the discussion in issue #996 you started a topic that needs to be explored.

You wrote:
I think logic that we have on top of calling Socket.ConnectAsync which handles cancellation after timeout is redundant. Consider using Socker.ConnectAsync overload that accepts CancellationToken and it will handle it.

**Comment by FanDjango** [comment]
> So we might even consider removing extra bits added on top of logic and just pass cancellation token which fires after timeout value.

I will need to research and analyze to fully understand that sentence*, but I have an inkling what you are getting at. It is just important to keep all edge cases in mind that have been there in the past and that led to some of the pieces of code that became redundant with later improvements in other areas.

*) Probably not the highest priority right now.

**Comment by FanDjango** [comment]
@vasyaxparfenov
Could you provide some example?

**Comment by vasyaxparfenov** [comment]
@FanDjango, sorry got lost a little bit. I'll send a code snippet with an example tommorrow.

**Comment by vasyaxparfenov** [comment]
@FanDjango, actually it turned out not that easy after all hah. Could you please tell me which version of dotnet were you using when experiencing timeout exception issues? Dotnet 6 and later has ConenctAsync overload which accepts cancellation token so we could avoid creating custom cancellation logic for latest version, but older version don't have such overload. We might consider checking whether socket was connected before trying to dispose it in case timeout occurs. Currently, our logic might break due to a fact that we're trying to close never opened socket.

**Comment by FanDjango** [comment]
I am closing this for now. I have been looking at the code and although there are still some places that don't look nice, we can leave them like that for now.
