### ISSUE TITLE
Proper handling of non-existing files/folders in Download API

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#1121]
## Current

Our current behavior if a file/folder does not exist:

- `DownloadDirectory` - returns blank list
- `DownloadFile` - returns Failed
- `DownloadFiles` - marks Failed 

All our API is not checking if something exists. Should we?

## Proposed

I think it would be better to:

- `DownloadDirectory` - if the root folder is missing throw `FtpDoesNotExist` error and mention folder does not exist
- `DownloadFile` - throw `FtpDoesNotExist` error and mention file does not exist
- `DownloadFiles` - mark the specific file as `IsFailed=true` and add the `FtpDoesNotExist` error in `Error` property. return list of `FtpResult` as usual.

## Rationale

Throwing an error is better than silently failing because if you are trying to download something that does not exist, it is an "exceptional case" imo and better to warn users and let them handle errors rather than silently failing and nobody having any idea that something went wrong.

**Comment by robinrodricks** [comment]
@FanDjango what are your thoughts?

**Comment by FanDjango** [comment]
I agree with your proposed actions.

If a caller **explicitly** states that he wants to **download** a specific _file_/_entire directory_ and this entity does not exist **remotely**, he is doing something that is in error.

If a caller **explicitly** states that he wants to **upload** a specific _file_/_entire directory_ and this entity does not exist **locally**, he is doing something that is in error.

If he wants to **download** a list of things, the returned results should just indicate failures - **missing on the remote** being one of them.

If he wants to **upload** a list of things, the returned results should just indicate failures - **missing on the local** being one of them.

If failures occurred, cleaning up (deleting successfully transferred files) should be made optional. The same goes for retrying transfers, because:

Failures that are deemed unrecoverable should terminate the operation prematurely, **not try to clean up** and throw an exception.

**Comment by robinrodricks** [comment]
Sounds good @FanDjango thanks for your thoughts, I'll work up a solution for the next major release.

**Comment by jnyrup** [comment]
I strongly agree in the thoughts from both of you.

**Comment by FanDjango** [comment]
I'd like to clarify my reasoning behind:

> If he wants to upload/download a list of things, the returned results should just indicate failures

Of course it could be a list of **explicitly** requested  items, and one would expect all of them to exist. Would one really? 

**No**, because acting on a list of items is often also associated with a purpose, namely "_try to get all of these files/this folder, dunno how many that may be or if they are all present_".

Or another way of looking at this, is: It is a sequence of single **explicit** transfers, which may fail, but the failure should try to carry on with the next in the sequence in case of a failure, unless that is no longer possible.

**Comment by robinrodricks** [comment]
Yes agreed @FanDjango

**Comment by robinrodricks** [comment]
Released!

https://www.nuget.org/packages/FluentFTP/44.0.0
