### ISSUE TITLE
New FtpSslSessionReuseException

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#1224]
@FanDjango what is your thought on absorbing errors like this and instead throwing a special exception with the exact advise you give out on the forums?

`SSL connection failed; session reuse required` -> `FtpSslSessionReuseException` which then has the message `"You need to 1) upgrade your FTP server to the latest or 2) disable SSL session reuse in your FTP server or 3) use FluentFTP.GnuTLS which supports SSL session reuse"`

It should reduce the workload of constantly answering the same damn thing when it comes up as a bug ticket.

What say? Is it possible? Is it viable?

**Comment by FanDjango** [comment]
Hi Robin,

 

excellent idea.

 

I sometimes prefer one or two lines of "ERROR" messages prior to a normal exception.

 

Also: Not every failure to authenticate the 2nd, 3rd, 4th, etc. connection (i.e. the data connection) is due to session resume problems, although we currently seem to be getting only these errors.

 

But by all means…

 

mit freundlichen Grüßen,

Michael Stiemke ***@***.***)

 

AnSyNova GmbH

Ringstr. 13

85405 Nandlstadt

+49 8756 969 49 79
<http://www.ansynova.com <http://www.ansynova.com/> >



 

From: Robin Rodricks ***@***.*** 
Sent: Wednesday, March 1, 2023 5:23 AM
To: robinrodricks/FluentFTP
Cc: FanDjango; Mention
Subject: [robinrodricks/FluentFTP] SSL connection failed; session reuse required (Issue #1224)

 

@FanDjango <https://github.com/FanDjango>  what is your thought on absorbing errors like this and instead throwing a special exception with the exact advise you give out on the forums?

SSL connection failed; session reuse required -> FtpSslSessionReuseException which then has the message "You need to 1) upgrade your FTP server to the latest or 2) disable SSL session reuse or 3) use GnuTLS to fix this"

What say? Is it possible? Is it viable?

**Comment by FanDjango** [comment]
excellent idea.



I sometimes prefer one or two lines of "ERROR" messages prior to a normal exception.



Also: Not every failure to authenticate the 2nd, 3rd, 4th, etc. connection (i.e. the data connection) is due to session resume problems, although we currently seem to be getting only these errors.



But by all means…

**Comment by FanDjango** [comment]
```
if (connection == data_connection)...
 {message with advice
 throw (possible resume failure exception)
}

**Comment by FanDjango** [comment]
Some more thoughts on this:

Quite a few cases exist where the SSL Authentication itself **does not** fail, but shortly after, there is a "4xx" message saying that it was not possible to open a data connection.

"Operation not permitted" is one such message, another actually refers to "session resume". There is a whole catalog of such messages, depending on the server type.

**Comment by FanDjango** [comment]
@4nd3r5 You might want to read through this issue

https://github.com/robinrodricks/FluentFTP/issues/948#issuecomment-1289708124

**Comment by FanDjango** [comment]
I have move this to the Wiki: https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans
