### ISSUE TITLE
High CPU acquiring socket, left in stuck state

### ISSUE THREAD

**Issue by TRMack** [robinrodricks/FluentFTP#1226]
**FTP Server OS:** Unix

**FTP Server Type:** BrickFTP

**Client Computer OS:** Windows Server 2018

**FluentFTP Version:** 44.0.1

**Framework:** .NET 7 (7.0.3 runtime)

We have a task that runs every night. This task creates a small text file and uploads it to the FTP server. Thousands of these tasks are spawned but only a handful run at time; typical runtime per task is a few hundred ms. 

3 times now in the last 3 months, we've noticed that one of the servers will experience high CPU usage (>90%) and we see that a few of these tasks are stuck in the queue having been running for several hours. I was able to grab a process dump most recently and it seems that the high CPU usage is spent on the FluentFTP.FtpSocketStream. I can provide the callstacks if helpful. It looks like the thread spins up and tries to acquire a socket and then hangs out in that state for several hours until the thread is killed and the task re-queued (at which point it runs and completes instantly, as it should).

Because multiple threads are running at the same time I'm having trouble separating out the logs for the tasks that got stuck (vs. the ones that continued on), but I can try if that's helpful. I'll improve our logging to avoid this issue in the future.

Has anyone else encountered this?

**Logs :**

```

<paste VERBOSE logs here>

```

**Comment by FanDjango** [comment]
You are welcome. Interesting factoid: The error was introduced (by me - sorry about that) quite a few months ago. Reports about this trundled in the first time about one or two weeks ago and I fixed it right away. If anyone had reported this _months ago_....

One thing you should know: Instead of a "hang" or even a "loop", the operation will timeout (as it should). I assume that your programming reacts to that in some way - you would not have experienced this fault if the transfer (all of them) would not incur  some error of whatever kind.

**Comment by FanDjango** [comment]
Also reference: #1222 #1203 #1156

**Comment by TRMack** [comment]
I should have reported it when we first noticed it months ago, but I assumed it was either an issue in our own code (forgetting to dispose somehow) or something in the runtime which is obviously under rapid development. Hate to assume that it's a particular library when my own code is the greater liability.

Thanks again for all your work. Will be sure to circle back with more info if it comes up again.
