### ISSUE TITLE
Dubious code in ConnectModule.IsPermanantConnectionFailure

### ISSUE THREAD

**Issue by fredericDelaporte** [robinrodricks/FluentFTP#1247]
**FTP Server OS:** No idea

**FTP Server Type:** `FileZilla Server 0.9.59 beta` as publicized by the server.

**Client Computer OS:** Windows 11

**FluentFTP Version:** 46.0.2

**Framework:** .NET 6

We had received once a failure from AutoDetect. The error was:
```
FluentFTP.Exceptions.FtpInvalidCertificateException: FTPS security could not be established on the server. The certificate was not accepted.
   at FluentFTP.Client.Modules.ConnectModule.AutoDetectAsync(AsyncFtpClient client, Boolean firstOnly, Boolean cloneConnection, CancellationToken token)
   at FluentFTP.AsyncFtpClient.AutoDetect(Boolean firstOnly, Boolean cloneConnection, CancellationToken token)
```

Looking at the code of `AutoDetectAsync`, it seems to throw directly only if `IsPermanantConnectionFailure` (sic, should be spelled `IsPermanentConnectionFailure`) has returned an exception.
https://github.com/robinrodricks/FluentFTP/blob/f2a171f83776e27f1d350a1ea3ae68b8e5a69f9e/FluentFTP/Client/Modules/ConnectModule.cs#L251-L260

Looking at `IsPermanantConnectionFailure`:
https://github.com/robinrodricks/FluentFTP/blob/f2a171f83776e27f1d350a1ea3ae68b8e5a69f9e/FluentFTP/Client/Modules/ConnectModule.cs#L372-L382
`FtpInvalidCertificateException` is supposed to only be thrown with an inner exception which could have provided more information. But unfortunately `FtpInvalidCertificateException` not only erases `Exception.InnerException` property but also do not call a base constructor allowing to set `Exception.InnerException`. As a result, standard exception logging cannot get the inner exception details.

See here:
https://github.com/robinrodricks/FluentFTP/blob/f2a171f83776e27f1d350a1ea3ae68b8e5a69f9e/FluentFTP/Exceptions/FtpInvalidCertificateException.cs#L15-L28

So, as the error only occurred once and do not reproduce, we cannot debug this, and the relevant information was lost due to the way the failing code path is coded.

By the way, reading a bit more the code of `IsPermanantConnectionFailure`:
https://github.com/robinrodricks/FluentFTP/blob/f2a171f83776e27f1d350a1ea3ae68b8e5a69f9e/FluentFTP/Client/Modules/ConnectModule.cs#L377-L392
We can see some dead code: the condition `ex is AuthenticationException authEx` can never be true since there is an early exit on that same condition written differently (`ex is AuthenticationException credEx`) a few lines above.

So, it looks to me that:
 - `FtpInvalidCertificateException` implementation should be reconsidered. Or at least it should have some comments added for explaining the reasons of hiding away `Exception.InnerException` and not calling a constructor taking the inner exception.
 - `IsPermanantConnectionFailure` needs some cleanup or corrections.

If there is no known reason for this implementation of `FtpInvalidCertificateException`, why not changing it to:
```c#
	public class FtpInvalidCertificateException : FtpException {

		/// <summary>
		/// Default constructor
		/// </summary>
		public FtpInvalidCertificateException(Exception innerException)
			: base(
				"FTPS security could not be established on the server. The certificate was not accepted.",
				innerException) { }
```

**Comment by FanDjango** [comment]
Thanks for this detailed analysis.

> IsPermanantConnectionFailure (sic, should be spelled IsPermanentConnectionFailure) 

I wish everything were as easy as fixing that one.

Now for the `IsPermanantConnectionFailure(...)`.

I have done some testing and to a certain extent I agree with some of your findings.

But first:

The purpose of this method is to abort connection attempts to a server if the type of failure indicates that there is no way to fix this by changing connection parameters.

One of the conditions is that the (deeper down) connection code, after connecting succesfully, cannot establish an SSL connection - the code that does that is `ActivateEncryption(...)` in `FtpSocketStream.cs`.

Sadly, .NET SslStream **does not** provide very detailed information about its failures, and these themselves, depending on framework, need to be gotten out of an inner exception themselves. Hence, in there, the exception is generated with as much information as possible in the message part of the exception, but there is not any inner exception used to transport further information (because there is none). 

The situation is more or less the same if you use GnuTLSStream, but then the message in the exception is much more detailed.

Here are examples for both SslStream and GnuTlsStream trying the same bound to fail autoconnect:

(I am catching this **prior** to calling `IsPermanentConnectionFailure(...)`)

SslStream:
![image](https://user-images.githubusercontent.com/51046875/232465602-ad538a94-04bf-42bd-9394-b2500bdf4872.png)

GnuTlsStream:
![image](https://user-images.githubusercontent.com/51046875/232466178-c191b334-ecaf-447c-90c2-14aec9caa491.png)

In both case, an `System.Exception {System.Security.Authentication.AuthenticationException}` with **no inner exception** and solely a message.

If there ever might have been an inner exception associated with `AuthenticationException` (and I have not seen one yet), **that** place is where it would have gotten lost in the first place.

I agree that the code in `IsPermanentConnectionFailure(...)` is somewhat dubious, and let's improve it. But I don't think it would have helped you diagnose the problem you mentioned.

Using GnuTlsStream with its **much** more detailed logging (up to showing the certificates involved in the authentication dialogue) would have helped but I don't think you would want to run a log with such detail for any amount of time.

**Comment by fredericDelaporte** [comment]
Thanks for your answer,

But it seems you have missed my point. I was not looking for the `InnerException` of the original exception which happens to be an `AuthenticationException`. I was looking for the `InnerException` of the later thrown `FtpInvalidCertificateException`, which should have been the original `AuthenticationException`.

But that information is lost due to the way `FtpInvalidCertificateException` is implemented. Even if the information of `AuthenticationException` is of little use, I do not think that is a valid reason for letting it get lost due to what looks to me as a bad implementation of the thrown `FtpInvalidCertificateException`.

That `FtpInvalidCertificateException` is built with the `AuthenticationException` as an argument, but it stores it in its own `new Exception InnerException` property shielding away the standard `Exception.InnerException` property instead of just calling its base constructor overload handling the `InnerException` properly. As a result, standard logging facilities just miss the original `AuthenticationException` which should have been available as an inner-exception of the thrown `FtpInvalidCertificateException`.

**Comment by Wiilf** [comment]
Smells like a GPT response. Just saying. Careful people. This is a solid library and the developers know what exactly their doing. And each release is based on user feedback. I feel that is a lot stronger than AI behind a smoke screen.

**Comment by FanDjango** [comment]
@fredericDelaporte I'll look at it some more. There are some quick and dirty ad-hoc things in there also, don't want to break them.

**Comment by FanDjango** [comment]
> `IsPermanantConnectionFailure` needs some cleanup or corrections.

Here is what I propose, essentially a reordering to address the issue of "dead code" that you mentioned.

```cs
		private static Exception IsPermanentConnectionFailure(Exception ex) {

			// Authentication related failures

			// catch unsupported protocol failure
			var msg = "Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'";
			if (ex.Message.Contains(msg) ||
				(ex is AuthenticationException authEx &&
					authEx.InnerException != null &&
					authEx.InnerException.Message.ToLower().ContainsAny(ServerStringModule.failedTLS))) {

				return new FtpProtocolUnsupportedException("Your server requires TLS 1.3 and FluentFTP does not currently support TLS 1.3 due to poor .NET support for this protocol.");
			}

			// catch credential related authentication failure (see issue #697)
			if (ex is FtpAuthenticationException credEx) {

				// only catch auth error if the credentials have been rejected by the server
				// because the error is also thrown if connection drops due to TLS or EncryptionMode
				// (see issue #700 for more details)
				if (credEx.CompletionCode != null && credEx.CompletionCode.StartsWith("530")) {
					return ex;
				}
			}

			// generic permanent authentication failure leftover: probably wrong FTPS certificate
			if (ex is AuthenticationException certEx) {
				return new FtpInvalidCertificateException(certEx);
			}

			// Network related failures

			// catch error "no such host is known" and hard abort
			if (ex is SocketException { SocketErrorCode: SocketError.HostNotFound }) {
				return ex;
			}

			// catch error "timed out trying to connect" and hard abort
			if (ex is TimeoutException) {
				return ex;
			}

			return null;
		}
```

**Comment by fredericDelaporte** [comment]
This looks sound. But I cannot tell if that is without unintended consequences. I have not studied the history of the code file to understand why it ended up with the code in this state. (That is what I would do if I was directly contributing, like I do where I contribute.)
