### ISSUE TITLE
Ability to upload a file that is currently open and being written to?

### ISSUE THREAD

**Issue by avoitenko** [robinrodricks/FluentFTP#1257]
**FTP Server OS: Windows
**FluentFTP Version: the latest
**Framework: .NET FRAMEWORK 4.8

Hello.

Trying to upload a file via FTP using 'UploadFile' function.
Returns with an excepton:
The process cannot access the file '...20230510.log' because it is being used by another process.

My offer is to make a small fix using FileShare.ReadWrite instead of FileShare.Read in the source file:
FtpFileStream.sc
function GetFileReadStream line 61
return new FileStream(localPath, FileMode.Open, FileAccess.Read, **FileShare.ReadWrite**, bufferSize, isAsync);

Thanks.

**Comment by robinrodricks** [comment]
How would this be a fix? If we need to just read a file, we should open it only for reading.

**Comment by avoitenko** [comment]
this is the correct line with fix
return new FileStream(localPath, FileMode.Open, FileAccess.Read, **FileShare.ReadWrite**, bufferSize, isAsync);

**Comment by FanDjango** [comment]
https://stackoverflow.com/questions/25097773/system-io-filestream-fileaccess-vs-fileshare

**Comment by FanDjango** [comment]
I assume you want to upload "...20230510.log" **from your system** to some server.

Next I assume you cannot access the file for read, because it is being written by some other process (seems like the log is still being written). Am I right?

So you want to be able to open it for reading, although it is currently being written to. Am I right?

That's what the FileShare.ReadWrite is for, as long as the user understands the caveats and the dangers.

**Comment by FanDjango** [comment]
Perhaps one would not want to have this setting permanently, but only as an option to avoid the typical pitfalls this could cause in normal usage?

**Comment by FanDjango** [comment]
Here is an excerpt with some more text on this topic:

QUOTE
You may need FileShare.ReadWrite if another process has already opened the file for writing. It already gained write access so you can never open the file yourself with just FileShare.Read, you can't deny writing since that other process was first, you'll be denied access instead. **This generally only comes to a good on a text file, the kind where you can be sure that the other process is only ever appending text to the end of the file. A log file is the very common scenario.** Still possibly tricky, it matters exactly when that process flushes changes to the file. You might observe partially written lines of text, beware of this.
ENDQUOTE

**Comment by avoitenko** [comment]
> I assume you want to upload "...20230510.log" **from your system** to some server.
> 
> Next I assume you cannot access the file for read, because it is being written by some other process (seems like the log is still being written). Am I right?
> 
> So you want to be able to open it for reading, although it is currently being written to. Am I right?
> 
> That's what the FileShare.ReadWrite is for, as long as the user understands the caveats and the dangers.

You are absolutely right.
I hope you reproduce this test case and realize that we failed with the exception.

**Comment by FanDjango** [comment]
> Perhaps one would not want to have this setting permanently, but only as an option to avoid the typical pitfalls this could cause in normal usage?

Need to think about this.

**Comment by FanDjango** [comment]
First of all, some more comments:

1. FileShare.ReadWrite, according to the official MS documentation, is to **allow** processes "coming after my open of the file" (i.e. "subsequent" opens) to **also** read or write the file.

If you consider that statement, you would think that actually the process that is writing to the log file, for example a log writer, **should open** with **FileShare.ReadWrite**. Then FluentFTP can open it for FileAccess.Read. So it is the log writer that should be changed.

But:

2. I have found numerous complaints against .DotNet that the real behaviour **is not totally according** to this documentation. I.e. FluentFTP must open with FileShare.ReadWrite to successfully read a file that someone has already opened for writing.

It is easy to test though, and when I have some time I will do that.

**Comment by FanDjango** [comment]
Currently, if you need this function ASAP, why don't you open the file yourself as a stream and then upload using FluentFTP? That would be a quick workaraound?

**Comment by FanDjango** [comment]
See #1266

**Comment by avoitenko** [comment]
> Currently, if you need this function ASAP, why don't you open the file yourself as a stream and then upload using FluentFTP? That would be a quick workaraound?

You mean like this, right?

```
using (FileStream fileStream = new FileStream(localPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite, bufferSize, false))
{
    status = client.UploadStream(fileStream, remoteFileName);
}
```

**Comment by FanDjango** [comment]
That was my idea, yeah.

**Comment by avoitenko** [comment]
> That was my idea, yeah. Why not try it?
Thanks. It works.

**Comment by FanDjango** [comment]
And this enhancement is also merged now.
