### ISSUE TITLE
PublishSingleFile does not work with fluentftp.gnutls libs

### ISSUE THREAD

**Issue by tts-sdrissen** [robinrodricks/FluentFTP#1347]
**FTP Server OS:** Unix / Windows

**Framework:** .NET 8

When I publish my project as SingleFile, there are 6 DLL files (libgcc_s_seh-1.dll, libgmp-10.dll, libgnutls-30.dll, libhogweed-6.dll, libnettle-8.dll, libwinpthread-1.dll) besides the EXE file.
I would expect that those files are bundled inside the EXE-file.

Both, IncludeAllContentForSelfExtract and IncludeNativeLibrariesForSelfExtract did not helped.

Do you have any idea?

**Comment by FanDjango** [comment]
This topic of getting the .dll files to be included (and in placed in the right path) on every single type of publish that there may be, is tricky and goes beyond my expertise.

> I would expect that those files are bundled inside the EXE-file.

I agree that it would be nice to have them "magically" be copied to wherever the need to go, and in this case also to be included in a "bundled" .exe file.

Perhaps someone else can chime in and help?

Until then, you may need to add some statements **to your** .csproj file to handle this. Once we know what is needed, we can perhaps take the next step, namely to provide such statement to dynamically added to the build step.

**Comment by tts-sdrissen** [comment]
Hi @FanDjango !
Thank you for taking a look at this.

I have an idea: When I open the nuget "fluentftp.gnutls.1.0.24.nupkg" with 7zip, I found: build\FluentFTP.GnuTLS.targets

This is the content of this file:
```
<Project>
  <ItemGroup>
    <Files Include="$(MSBuildThisFileDirectory)/../content/*.dll" />
  </ItemGroup>
  <Target Name="CopyFilesBuild" AfterTargets="Build">
    <Copy SourceFiles="@(Files)" DestinationFolder="$(TargetDir)" />
  </Target>
  <Target Name="CopyFilesPublish" AfterTargets="Publish">
	<Copy SourceFiles="@(Files)" DestinationFolder="$(PublishDir)" />
  </Target>
</Project>
```

I suspect that the files are not embedded because they are only added after building and publishing (see AfterTargets).
Is this NuGet Package available as a github repo, so I can fork and modify it, or do I have to modify the nupkg-file to test my assumption?

Assuming that helps - do you have any idea how to tell the Nuget package to configure whether to embed the DLL files or not (as before)?
There must be a better way than offering a second Nuget package to embed the DLLs.

**Comment by FanDjango** [comment]
> `build\FluentFTP.GnuTLS.targets`

Without this file, the DLL files were not being added at all to any bundle.

We have our package build put this file in the NuGet package to be referenced by the users build.

Perhaps we just need to add "PublishSingleFile" as an additional target in this file?

> Is this NuGet Package available as a github repo, so I can fork and modify it, or do I have to modify the nupkg-file to test my assumption?

Yes, you can find it under [FluentFTP.GnuTLS](https://github.com/robinrodricks/FluentFTP.GnuTLS)

> There must be a better way than offering a second Nuget package to embed the DLLs.

I am not sure I understand this statement. But we did separate out the FluentFTP.GnuTLS wrapper because of license concerns, it wasn't technical at all. 

This separation of course is the reason why having the foreign DLLs copied in to the right place is so difficult, as it seems to be a "two stage" operation.

**Comment by tts-sdrissen** [comment]
Let me share what I have learned:
It did not help to copy the files before build or before publish. 
But if there is a folder "runtimes" in the nuget package, the files are included in the exe.
The file structure have to be like this:
```
+---runtimes
|   +---linux-x64
|   |   \---native
|   |           libgcc_s_seh-1.dll
|   |           libgmp-10.dll
|   |           libgnutls-30.dll
|   |           libhogweed-6.dll
|   |           libnettle-8.dll
|   |           libwinpthread-1.dll
|   |
|   +---osx-x64
|   |   \---native
|   |           libgcc_s_seh-1.dll
|   |           libgmp-10.dll
|   |           libgnutls-30.dll
|   |           libhogweed-6.dll
|   |           libnettle-8.dll
|   |           libwinpthread-1.dll
|   |
|   +---win-x64
|   |   \---native
|   |           libgcc_s_seh-1.dll
|   |           libgmp-10.dll
|   |           libgnutls-30.dll
|   |           libhogweed-6.dll
|   |           libnettle-8.dll
|   |           libwinpthread-1.dll
|   |
|   \---win-x86
|       \---native
|               libgcc_s_seh-1.dll
|               libgmp-10.dll
|               libgnutls-30.dll
|               libhogweed-6.dll
|               libnettle-8.dll
|               libwinpthread-1.dll
```

However, at the moment I cannot present a solution that allows you to deliver the files without embedding them. If the files are placed in the "runtimes" folder, they are always embedded. You could currently embed the files and deliver them, but not "only deliver them", which would increase the total files size.

The lazy solution is to offer two Nuget packages. One for embedding and one for "delivering as files".  But I'm not convinced of this solution myself.

Let me know, how you feel about my insights.

**Comment by FanDjango** [comment]
Please be aware of the FluentFTP.GnuTls config parameter ` LoadLibraryDllNamePrefix = "Libs\\Win64",`, it might help.

I have been expermenting with publishing and as soon as I specify "Single File" the .dlls are missing entirely, though.

**Comment by FanDjango** [comment]
Reading [this](https://community.esri.com/t5/net-maps-sdk-questions/publish-single-executable-not-working-for-net-5-or/td-p/1136336) was intriguing as well.

**Comment by FanDjango** [comment]
You might want to read a little on #1425, same problem there. PublishSingleFile behaves strangely. Like you noticed, it simply ignores ` <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>`, for example.

In the internet there are people saying that this worked for them, but... some time ago.

I am losing patience with this. An after-build (and pre-publish) step won't help. I tried it. It is the part of the publish that builds the single file that is simply doing something wrong. It looks like it directly accesses the NuGet package and ignore the contents of the app.publish folder. 

Could it be that the folder structure you mentioned is sort of hard coded into that publishing code? That will be my last try then tomorrow, to somehow produce that kind of structure in NuGet, for that I must change the Build for FluentFTP.GnuTLS to sort of "produce" that. I have been trying that for so long today, maybe I'll have a new insight on the morrow.

**Comment by FanDjango** [comment]
> I suspect that the files are not embedded because they are only added after building and publishing (see AfterTargets).

I had the same idea, too. I just wanted to add that I read that and today I changed that to "BeforeTarget=BeforePublish". And it didn't help. After Build is fine, but before Publish is correct - but sady it didn't change anything.

I think it is because the single-file-builder grabs stuff out of the NuGet and uses that.

**Comment by FanDjango** [comment]
I found this and it confirms your runtimes folder structure. 

https://github.com/Apollo3zehn/EtherCAT.NET/blob/1ecc3c751736e9526543b0bd8415e3c0597aed3a/src/SOEM.PInvoke/SOEM.PInvoke.csproj#L15-L28

**Comment by tts-sdrissen** [comment]
> You might want to read a little on #1425, same problem there. 

Hmh. I just read that. I didn't test it yet, but I suspect, that the "runtimes" folder structure would also solve the problem of this guy.
With the downside, that the DLLs would be included in the EXE (or main DLL, if it was not single File), and the DLLs would be also included for reference, which would increase the total file size, because the GnuTLS DLLs would be included twice.

> Reading [this](https://community.esri.com/t5/net-maps-sdk-questions/publish-single-executable-not-working-for-net-5-or/td-p/1136336) was intriguing as well.

I work on this problem for 2 weeks now... At some point I copied IncludeAllContentForSelfExtract and IncludeNative... into both: csproj and pubxml. Without success.

> Please be aware of the FluentFTP.GnuTls config parameter ` LoadLibraryDllNamePrefix = "Libs\\Win64",`, it might help.
> 
> I have been expermenting with publishing and as soon as I specify "Single File" the .dlls are missing entirely, though.

Yeah. They missing entirely... It is not like they are in some other folder, I think LoadLibraryDllNamePrefix will only be considered on runtime. So I don't think, this will help in this case.

> Could it be that the folder structure you mentioned is sort of hard coded into that publishing code? 

As I said, for now, I have not entirely figured it out, how a Nuget Package is processed. Maybe (you may hate this word) there is another possible folder like "runtimes". 

The good news is: It has to work somehow. It is possible. The Nuget Package for Sqlite do it exactly like this. There is a native DLL named SQLite.Interop.dll and it can be embedded - or not.
I am currently analyzing Stub.System.Data.SQLite.Core.NetFramework - maybe I find something there...

> I am losing patience with this.

I think, it is a good opportunity for me to learn the mechanics behind Nuget Packages... And I hope I come up with a good solution soon.

**Comment by tts-sdrissen** [comment]
Ok... The targets file in Stub.System.Data.SQLite.Core.NetFramework has 70 effective lines plus some comments...

Got some insights... Like they used "DependsOn" like "BuildDependsOn" and not "BeforeBuild".
And they copy the DLL also on CleanDependsOn - not sure why...
And they use "PipelineCollectFilesPhaseDependsOn" - which sounds important...
And they consider "per-user settings": "If the per-user settings file exists, import it now."... I think for the switches. Like you can control, how the DLL should be included...

But... There is also a Stub.System.Data.SQLite.Core.Net**Standard** Version for .NET Core.
And this .NET Core Version only uses the "runtimes"-folder mechanism. 
This makes me worried, that there maybe isn't a unified solution for .NET Framework and .NET Core. 
But the delivered DLL differs in size, so maybe **those** are not intercompatible between .NET Framework and .NET Core
But how can a unmanaged DLL not be compatible? 

... "Just fishin' in the dark, son."

By the way? Did you test FluentFTP.GnuTLS with .NET Standard **AND** .NET Core?
Or is .NET Core supported only anyway?

**Comment by FanDjango** [comment]
Net Framework and Net 5, 6, 7, 8 and Net Standard

**Comment by FanDjango** [comment]
I spent another whole day on this.

Duplicating all sorts of folder structures did not help.

What I **actually did achieve**:

_After learning a lot about all this, I was able to reduce the size of the GnuTLS NuGet significantly by not duplicating the .dlls for all different TFMs (net5.0, net6.0 etc. etc.) in "contentFiles"._

Take a SDK style project that installs the GnuTLS NuGet (together with FluentFTP, of course). Do a debug or release build. The .dlls will have been copied into the bin/Debug|Release/net5.0/ folder, and it works fine.

Now do a publish (set it to publish to a folder, or to ClickOnce, but don't choose Single File). The .dlls are taken from the contentFiles folder and they appear in the app.publish folder. Then they appear in the win-x64 folder, and so on until the application is finally put together. Play around with the different possibilites and you will see that the last process, the one that produces the single file (compress and bundle), it does not pick up the .dlls. Non-single file to a folder works, anything else does not.

I can get all sorts of stuff, as well as the .dlls to be included. By coding a <content include=".....">. The trouble with that though, is that this copies the files in and preserves the folder structure at the destination, which I do not want. I need the files to be placed in the top directory.

To even get this far, it was necessary to work with the .csproj file of the app, not with the NuGet organisation, which is fine as it is.

Note: I have never ever used ClickOnce - thank God I didn't ever fall into that trap. I immediately started using Post-Build Events (a script) and InnoSetup, highly programmable and customizable.

**Comment by FanDjango** [comment]
I have put together a final NuGet related release of FluentFTP.GnuTLS (1.0.28) and it integrates well into a test application that references packages FluentFTP and FluentFTP.GnuTLS.

When building the test app (NET 8.0):

On a debug build, all the dll files are where they are needed (i.e. in the output folder where the .exe file is to be found).

On a release build, all the dll files are where they are needed. (i.e. in the output folder where the .exe file is to be found).

When using "publish":

Publish to a folder works fine, the test app works correctly when run. Dll files are in the right place.

Publish to ClickOnce also works fine **as long as** you do not select SingleFile., you can install the app and it runs ok.

_So: SingleFile does not transfer the content dll files to the bundling folder as opposed to what the non-SingleFile process does._

In the FluentFTP.GnuTLS Nuget package, all the needed files are present.

It really boils down to the user having to code the right statements **in his own applications** .csproj to make this work. What are the right statements? We do not know - research in the Web has provided contradictory information. 

If we knew what is missing in the **apps .csproj** (NOT in the FluentFTP.GnuTLS .csproj) to fix this, we could of course put that in the NuGet package build folder to be _injected_ into the apps .csproj file transparently to the user.

For now, I am once again passing this on to those who have more time for this, perhaps to even open an issue with MS.

**Comment by FanDjango** [comment]
Just a quick update: I have found the solution. In the next days I will finalize it and show the way to do it here.

**Comment by FanDjango** [comment]
I found out how this is to be done, have made the necessary changes and I can explain the problem.

**First:** ClickOnce Publish Single File will deploy a "single file bundle", when the app is installed and run, it will be expanded to a temp directory. This directory is **not** the directory that the app was started from, thus the standard dll search will not find any native resources.

The dlls are **actually** incuded in the bundle - they are not missing. Try it with a huge dummy dll and you can see the change in size. The dlls were simply not being found.

I have modified FluentFTP.GnuTLS so that if you specify a special config parameter, it will dynamically find out and add this temp directory into its dll load regime. Specify the config parm 
```cs
LoadLibraryDllNamePrefix = "ClickOnceSingleFile"
```
as a "special" prefix - FluentFTP.GnuTLS will recognize this as an instruction to determine the path of the temp directory and to prefix that to the dll filenames.

**However, this is not all you must do:**

FluentFTP.GnuTLS packaging stores the native dlls under "contentFiles" in the Nuget package. Thus you need to specify
```cs
	<PropertyGroup>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	</PropertyGroup>
```
Do not specifiy `<IncludeNativeLibrariesForSelfExtract>` as `true`, even if this is suggested in many places in the internet. The dlls are classed as "content", not located in runtimes (so no "runtimes\<rid>\native" folder etc.).

**And incidentally**, you need to install **FluentFTP.GnuTLS 1.0.29** or higher. Earlier versions do not have this capability.

**Comment by FanDjango** [comment]
I wanted to document the tricks I needed to find out the stuff I wrote in the previous post.

I put together a minimum NET 8.0 console app ("Hello world") and added one (totally uneeded and unused) dll to the project, in the root dir of the app. I chose the biggest dll ( about 500k ) that I could find in the different folders under C:\Programs. It is totally irrelevant what this dll is. It is just a dummy.

CO (= ClickOnce) publish, single file **with this dll** and **without** compared against each other, differ significantly in size. So, I concluded that the dll(s) are actually being included, even if I can't really see them anywhere (especially when I install the CO app).

I then put together a minimum NET 8.0 console app that will output the contents of the current directory, i.e. where the exe itself is running and I installed the FluentFTP.GnuTLS Nuget package into it. Why? Well that is **one** of the places where [DllImport...] will search for the dlls. And I would like to see if the dlls are actually decompressed there, are they to be found?

```cs
        static void Main(string[] args)
        {
            string strExeFilePath = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string strWorkPath = System.IO.Path.GetDirectoryName(strExeFilePath);

            Console.WriteLine(strExeFilePath);
            Console.WriteLine(strWorkPath);

            DirectoryInfo d = new DirectoryInfo(strWorkPath);
            FileInfo[] Files = d.GetFiles("*.*");

            foreach (FileInfo file in Files)
            {
                Console.WriteLine(file.Name);
            }
            Console.ReadLine();
etc.
etc.
```

Scrolling through the output, I could see the 6 dlls. 

I also noticed that the directory name **was not the directory name** where the app was installed to by CO.

```
C:\Users\xxxx~1\AppData\Local\Temp\.net\FluentFTP.PackagingTest\FHkrOsEzuWUVQFxbClcHDIm49rLsxBw=\FluentFTP.PackagingTest.dll
C:\Users\xxxx~1\AppData\Local\Temp\.net\FluentFTP.PackagingTest\FHkrOsEzuWUVQFxbClcHDIm49rLsxBw=
FluentFTP.dll
FluentFTP.GnuTLS.dll
FluentFTP.PackagingTest.deps.json
FluentFTP.PackagingTest.dll
FluentFTP.PackagingTest.runtimeconfig.json
libgcc_s_seh-1.dll
libgmp-10.dll
libgnutls-30.dll
libhogweed-6.dll
libnettle-8.dll
libwinpthread-1.dll
Microsoft.CSharp.dll
etc.
etc.
```

Note the ...\AppData\Local\Temp.. and that the dlls are present.

If you use the task manager to show the execs path (while the console window is open) you can see the location of the exec. You will see it is in ...\AppData\Local\Apps\..... !!!

You suddenly realize that the dll search will not find the dlls, because that directory **does not contain** the apps. It only contains the **not yet expanded** app.

Add an FTP client to our little console app and use `Procmon64.exe` (www.sysinternal.com) to check the search process for the dlls confirms: All fail.

![image](https://github.com/robinrodricks/FluentFTP/assets/51046875/ddce91b0-40d0-4324-970c-0feed13eba77)

After that and some experimenting, I realised that we need a way to tell our dll loader **where** to look. Not in the standard places, but in a totally new place. The rest was easy.

**Comment by tts-sdrissen** [comment]
Sorry for the delay. I was busy with holidays.

> CO (= ClickOnce) publish, single file **with this dll** and **without** compared against each other, differ significantly in size. 

I am not sure, if you confused this issues with issue #1425 ... One could argue about whether OneClick setups are as good or better than SingleFiles, but it's not the same. Nonetheless, it works!

> I have modified FluentFTP.GnuTLS so that if you specify a special config parameter, it will dynamically find out and add this temp directory into its dll load regime. Specify the config parm

Ok... I choosed this code to test, if it works: Yes, it works. Is it enough to just specify "LoadLibraryDllNamePrefix" and the other settings will default to the "not custom behavior"?

```
var gnuTlsStream = new FluentFTP.GnuTLS.GnuTlsStream();
var customGnuConfig = new GnuConfig()
{
    LoadLibraryDllNamePrefix = "ClickOnceSingleFile"
};
var customFtpConfig = new FluentFTP.FtpConfig
{
    CustomStreamConfig = customGnuConfig
};

gnuTlsStream.Init(new FluentFTP.Client.BaseClient.BaseFtpClient(customFtpConfig), "", new System.Net.Sockets.Socket(SocketType.Stream, ProtocolType.Tcp),
                  new CustomRemoteCertificateValidationCallback((sender, certificate, chain, policyErrors) => {
                      return true;
                  }), true, null, customGnuConfig);
```

> Do not specifiy `<IncludeNativeLibrariesForSelfExtract>` as `true`, even if this is suggested in many places in the internet.

On that note: I specified it as `false` and got this error message:
```
If all content is included, native libraries are also included.
If "IncludeAllContentForSelfExtract" is set to TRUE, "IncludeNativeLibrariesForSelfExtract" must not be FALSE.
```
(I translated this to english as my language is german. )
So I assume "undefined" will default to true.

> So: SingleFile does not transfer the content dll files to the bundling folder ...

I am not entirely sure, if this is some kind of the root problem. I told you, that it worked with the "runtimes"-folder in the Nuget Package, even if I could not manage to make it work, as "not embedded". It worked without modifications in the GnuConfig. ...
I think, that it is not intended this way... But it is the best way we got at the moment.

All in all - good stuff! Great work! Nice end of 2023! 

I will include it in my main project and hope for the best.

**Comment by FanDjango** [comment]
> Is it enough to just specify "LoadLibraryDllNamePrefix" 

It is enough

> I am not sure, if you confused this issues with issue https://github.com/robinrodricks/FluentFTP/issues/1425

I confused the two

> On that note: I specified it as false and got this error message:

Doesn't happen for me - I was testing on NET 8.0 - 6.0 - I have never seen these error messages.

>  I told you, that it worked with the "runtimes"

Yes, that is one way to do it - it would need just a small copy step in the build process. If you put one together and it works, we can then put into the Nuget package as an additional target. I tried it, but didn't work for me. So I went that other direction...

> So I assume "undefined" will default to true.

I tried all 4 possible combinations of true and false for the two paramrters and also leaving them out completely ( = 6 combinations :-) ). Specifiying ONLY the one was the only one that worked for me.

**Comment by FanDjango** [comment]
Note that regardless of CO or SingleFile or whatever:

Simply checking by some Nuget explorer or unzip program to see if the dll's are actually included in the "deployment" file is only **one of the steps** required to see if the dlls are being deployed.

The next step is to use a trick like the above console program do display the current directory of the executable, to see **if the dlls have then been expanded** to a location (and where, perhaps) on installation of the app.

And then, the dlls need to be found by the DllImport mechanism - and since this is not a permanent path FluentFTP.GnuTLS needs to **told what to do, to find them**", as opposed to the normal way.

Searching the internet for this topic in general, I noticed that how this works (e.g. runtimes, content, etc.) is a evolutionary thing that has not yet reached its cusp - and supporting NET back to Framework 4.6.2 as well as NET 6.0 etc. is probably "difficult", to say the least.

**Comment by FanDjango** [comment]
Ok. Super. Does that mean that your app (32bit) is then calling into 64bit? Didn't know that would work?

**Comment by AlexZonov** [comment]
There are no libraries for different architectures in the nuget package. I just get them and use.

![image](https://github.com/user-attachments/assets/e3cd17fe-69bb-4fe9-8aed-06ff67e2ab38)

**Comment by FanDjango** [comment]
All is good. I mistook your post for a different issue and deleted it. `LoadLibraryDllNamePrefix` : Yes, that`s what I made it for.
