### ISSUE TITLE
DownloadFiles vs. DownloadFile discrepancy in return type/value

### ISSUE THREAD

**Issue by PrzemyslawKlys** [robinrodricks/FluentFTP#1360]
As part of:
- https://github.com/robinrodricks/FluentFTP/issues/1356

I've found the hard way the API changed and you now return proper object when using `DownloadFiles`

```powershell
 $Message = $Client.DownloadFiles($LocalPath, ([string[]] $FileToDownload), $LocalExists, $VerifyOptions, $FtpError)
```

But it seems you continue to return string as part of `DownloadFile`. I think it would make sense to fix this disprepancy and have both act the same way?

**Comment by FanDjango** [comment]
> I've found **the hard**  way the API changed

That is entirely a matter of opinion. Sometime an API change is needed, but it is actually easy to see that, because we use a sensible versioning scheme ( 44.x.x -> 48.x.x ).

> But it seems you continue to return string as part of DownloadFile

Huh? 

```cs
public FtpStatus DownloadFile(string localPath, string remotePath, FtpLocalExists existsMode = FtpLocalExists.Overwrite, FtpVerify verifyOptions = FtpVerify.None, Action<FtpProgress> progress = null) {

public List<FtpResult> DownloadFiles(string localDir, IEnumerable<string> remotePaths, FtpLocalExists existsMode = FtpLocalExists.Overwrite, FtpVerify verifyOptions = FtpVerify.None, FtpError errorHandling = FtpError.None, Action<FtpProgress> progress = null, List<FtpRule> rules = null) {
```

> have both act the same way?

One is a `FtpResult`, the other a `List<FtpResult>`. Are you saying, you want a list for DownloadFile as well, with only one list element?

**Comment by PrzemyslawKlys** [comment]
> > I've found **the hard**  way the API changed
> 
> That is entirely a matter of opinion. Sometime an API change is needed, but it is actually easy to see that, because we use a sensible versioning scheme ( 44.x.x -> 48.x.x ).

Don't get me wrong. It was entirely my fault. I wast just referencing issue. 

As for the other issue (straight from your screenshot) :-) 

![image](https://github.com/robinrodricks/FluentFTP/assets/15063294/45c303ad-ddea-4d95-92f2-792d2e339e20)

What I am saying is I get FtpStatus enum, rather than FtpResult

![image](https://github.com/robinrodricks/FluentFTP/assets/15063294/405f7442-c834-4fc4-b016-df02ffa59a27)

And I can see that when running code.

**Comment by FanDjango** [comment]
Oh shit. I need new glasses.

**Comment by FanDjango** [comment]
I am also of the opinion that this can be improved.

I think that this will be put on the "enhancement" - "todo" list, as it will be a disruptive change if there is agreement to do this.

**Comment by FanDjango** [comment]
Moved to Wiki

**Comment by robinrodricks** [comment]
@PrzemyslawKlys I was about to implement this but the changes required are a lot and the result is fundamentally different for a very simple reason. They both behave differently:

- **DownloadFile**
  - Throws exceptions for errors (important also as these exceptions are caught by higher-order functions like DownloadFiles)
  - `RemotePath` and `LocalPath` are already provided to it, so it does not need to return it
  - `IsSkipped` is out of the question, no mechanism for filtering files
  - `IsFailed` is not required, just throws exceptions on failure
  - `Type` and `IsDownload` are irrelevant, you know it is a file being downloaded

- **DownloadFiles**
  - Does NOT throws exceptions for errors because otherwise the entire function would abort and we instead resume on errors and just skip the failing file
  - `RemotePath` and `LocalPath` are NOT provided by the caller, but instead computed by the function, so it makes sense to return it back to the user
  - `IsSkipped` is set when the file is filtered by rules
  - `IsFailed` is required, because exceptions are not used to indicate a file was failed
  - `Type` is used to indicate if its a file/folder/link

So for these reasons I see no reason why we should return a `FtpResult` from `DownloadFile` or `UploadFile` but thanks for your suggestion.

**Comment by robinrodricks** [comment]
Added FAQ here.

https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#why-does-downloadfile-and-downloadfiles-return-a-different-data-type

**Comment by robinrodricks** [comment]
@PrzemyslawKlys Released.

https://www.nuget.org/packages/FluentFTP/48.0.2

- New: `FtpResult.ToStatus()` API to easily compare result values of `DownloadFile`/`DownloadFiles` and `UploadFile`/`UploadFiles`

 Does this help?

**Comment by PrzemyslawKlys** [comment]
I already have simple logic that based whether it's success or not, it creates fake properties. 

- https://github.com/EvotecIT/Transferetto/blob/master/Private/Get-PrivateFTPFile.ps1

So i'm fine with your decisions, just I know users in PowerShell prefer same output, especially that I don't separate 1 file vs multiple files and I keep them under single command, and depending whether you pass 1 or multiple files it goes one way or the other.
