### ISSUE TITLE
IBM FTP Server returns error: File must be specified by library/file.member

### ISSUE THREAD

**Issue by anandgmenon** [robinrodricks/FluentFTP#1385]
**FTP Server OS:** IBM AS400

**FTP Server Type:** IBM OS400

**Client Computer OS:** Windows

**FluentFTP Version:** Tried with 47.1.0/48.0.3 (same behaviour on both)

**Framework:** .NETCore3.1

I am from Azure logic Apps team. We use the library in the FTP connector there. We have a customer who faces the error `File must be specified by library/file.member` regularly in different operations. 
The customer had an older version earlier 35.2.2 and the issue wasn't happening there. Also upon further investigaton, we noticed this only happens when we use `OpenRead()` on the same connection and we also see some stale data in the logs, so probably has something to do with OpenRead and stale connections. Sharing the entire logs below. Let me know if you need anymore information

**Logs :**

[logs-ftp.txt](https://github.com/robinrodricks/FluentFTP/files/13472580/logs-ftp.txt)

**Comment by FanDjango** [comment]
OpenRead is marked as "obsolete" (since V40, I think, or even earlier?). And yes, that code has changed from V35.2.2 - OpenRead, **if you must, if you insist** on still using it, you must add your own `GetReply(...)` statement to avoid stale data.

**Comment by anandgmenon** [comment]
Thanks @FanDjango for the quick reply. Yeah, I know OpenRead is obslelete, but I don't see any other alternatives for the streaming use case we have. So we'll have to continue to use OpenRead, I'll check implementing a GetReply() to see if that works for us.

**Comment by FanDjango** [comment]
I suppose we can close this then?

**Comment by anandgmenon** [comment]
Yes, you can close it, we are implementing the changes as suggested by you, we can reopen if we see further issues

**Comment by anandgmenon** [comment]
@FanDjango, here's the [logs](https://github.com/robinrodricks/FluentFTP/files/13728137/ftp-IBM.txt) after adding the GetReply() methods to OpenRead. We still see some stale data which might be causing the original `501 File must be specified by library/file.member.` error.

```
2023-12-19 15:03:06.4467879	 Message: >         GetListing(""/E920/PY920/Export/Concur"", Auto)"
2023-12-19 15:03:06.4468950	 Message: >         OpenDataStreamAsync(""LIST /E920/PY920/Export/Concur"", 0)"
2023-12-19 15:03:06.4469782	 Message: >         OpenPassiveDataStreamAsync(AutoPassive, ""LIST /E920/PY920/Export/Concur"", 0)"
2023-12-19 15:03:06.4470264	 Message: Status:   Socket has stale data - prior to command execution
2023-12-19 15:03:06.4471670	 Message: Status:   The stale data was: 
2023-12-19 15:03:06.4501690	 Message: Warning:  Reconnect needed due to stale data present on control connection (SslSessionLength: 338)
2023-12-19 15:03:06.4502043	 Message: Status:   Command stashed: EPSV
2023-12-19 15:03:06.4502405	 Message: Status:   Closing/Disposing FtpSocketStream(control connection)
2023-12-19 15:03:06.4509381	 Message: >         Connect(True)
```
Could you reopen and take a look at this one too? Not sure if this has the same symptoms of #1410

**Comment by FanDjango** [comment]
```
2023-12-19 14:53:14.8687711	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Response: 226 File transfer completed successfully. [173ms]
2023-12-19 14:54:28.5149392	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 14:55:28.5133278	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 14:56:28.5202778	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 14:57:28.5228481	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 14:58:28.5117976	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 14:59:28.5234663	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 15:00:28.5226279	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 15:01:28.5357484	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 15:02:28.5197137	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 15:03:06.4465349	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 15:03:06.4467879	"ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: >         GetListing(""/E920/PY920/Export/Concur"", Auto)"
2023-12-19 15:03:06.4468950	"ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: >         OpenDataStreamAsync(""LIST /E920/PY920/Export/Concur"", 0)"
2023-12-19 15:03:06.4469782	"ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: >         OpenPassiveDataStreamAsync(AutoPassive, ""LIST /E920/PY920/Export/Concur"", 0)"
2023-12-19 15:03:06.4470264	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Socket has stale data - prior to command execution
```
Same as #1324 
I'll add one more comment in that issue instead of here.

**Comment by FanDjango** [comment]
Please read our Wiki [on AS/400](https://github.com/robinrodricks/FluentFTP/wiki/IBM-zOS-and-OS-400-Support) and do a

SITE NAMEFMT 1

**Comment by FanDjango** [comment]
@anandgmenon I reopened to make sure you see this. We can close again once you confirm.

This issue was a bit of a double / mixup.

First, came the problems with the stale data, because you were using the obsolete `OpenRead....`.

```2023-12-19 15:03:06.4469782	"ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: >         OpenPassiveDataStreamAsync(AutoPassive, ""LIST /E920/PY920/Export/Concur"", 0)"
2023-12-19 15:03:06.4470264	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Socket has stale data - prior to command execution
```
Well, you were not picking up the reply `501 File must be specified by library/file.member.` 

Once you fixed the original problem (in your code), you now see the **actual** error _that was hiding behind this_ (i.e. 501 File must be specified by library/file.member.) 

This once again is an error that you can fix with "SITE NAMEFTM 1".

**Comment by FanDjango** [comment]
If you had coded the "SITE NAMEFMT 1" from the beginning, you might NEVER have seen the stale problem - which would have been potentially a danger lurking there for the future.

**Comment by anandgmenon** [comment]
@FanDjango thanks for the explanantion. Couple of questions on this actually
- The error `501 File must be specified by library/file.member.` seems to only happen when used along side OpenRead (regarless of whether we use `GetReply` there) and doesn't seem to happen when used along side other methods .
- The issue also didn't happen with 35.x verion of FluentFTP.
Any ideas what could be the reason for these symptoms?

Also is there a client configuration we can use as an alternative to `SITE NAMEFMT 1`. Looks like for some reason the customer can't set `SITE NAMEFMT 1`

**Comment by FanDjango** [comment]
> The error 501 File must be specified by library/file.member. seems to only happen when used along side OpenRead (regarless of whether we use GetReply there) and doesn't seem to happen when used along side other methods .

```
2023-12-19 15:03:07.3728120	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Command:  LIST /E920/PY920/Export/Concur
2023-12-19 15:03:07.3729404	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Status:   Waiting for response to: LIST /E920/PY920/Export/Concur
2023-12-19 15:03:07.4124117	ClientId: 711fa08f-c6d8-449b-91eb-14b062b1af1a Message: Response: 501 File must be specified by library/file.member. [39ms]
```
I beg to differ :-)

> The issue also didn't happen with 35.x verion of FluentFTP.
Any ideas what could be the reason for these symptoms?

As I said, in those days OpenRead probaly did a GetReply, before being declared obsolete? But if that were the case, you would have seen the 501 message. I rather think that the 501 message was not being retrieved at all.

Now that we better logic in this process, it is being retrieved and shown.

> Also is there a client configuration we can use as an alternative to SITE NAMEFMT 1

Not really. NAMEFMT 1 is as close to a unix kind of filename syntax as possible, making the pasrsing of a LIST output easier.

** Let's analyze some more, using your last included log**

I have taken a small excerpt, heavily edited. Look:
```
GetObjInfo:

> GetObjectInfo(""/E920/PY920/Export/Concur/list_p0087588bldj_20230327111206.txt"", False)"
> GetListing(""/E920/PY920/Export/Concur"", Auto)"
Command:  LIST /E920/PY920/Export/Concur
Listing:  -rwxrwx---   1 EDIUSER2 0           1241 Dec 19 09:53 list_p0087588bldj_20230327111205.txt
Listing:  -rwxrwx---   1 EDIUSER2 0           1241 Dec 19 09:53 list_p0087588bldj_20230327111207.txt
Listing:  -rwxrwx---   1 EDIUSER2 0           1241 Dec 19 09:53 list_p0087588bldj_20230327111206.txt
Response: 250 List completed. [174ms]
Warning:  Failed to get object info for path /E920/PY920/Export/Concur/list_p0087588bldj_20230327111206.txt since MLST not supported and GetListing() fails to list file/folder.
-->PROBLEM #1

Then OpenRead:
RETR /E920/PY920/Export/Concur/list_p0087588bldj_20230327111206.txt
150 Retrieving file
226 File transfer completed successfully. [173ms]

Then
GetListing(""/E920/PY920/Export/Concur"", Auto)"  NOTE: same GetListing as used inside GetObjInfo
Socket has stale data - prior to command execution NOTE: something is STILL left over after the OpenRead RETR
-->PROBLEM #2

Then reconnect etc. etc. 

Then GetListing(""/E920/PY920/Export/Concur"", Auto)"  NOTE: same GetListing as used inside GetObjInfo
Response: 501 File must be specified by library/file.member. [39ms]
-->PROBLEM #3
```

So:
#2 Something is still not quite clean after the RETR (from OpenRead). There is stale data, but it seems empty or contains hex zeros or whatever. A **second** might help? Not using OpenRead, but DownloadFile instead might help? 

The stale data causes the GetListing to recognize this situation and to do a reconnect first. That works fine and is not a problem, just an incidental symptom that doesn't interfere with the next thing thst happens:

The GetListing is now repeated (as it should be), and this GetListing gets a nice error message. It is the same GetListing as in the GetObjectInfo, which as you can see, also allegedly failed.

#1 Something is wrong with the ObjectInfo API function - it is successful and doesn't seem to notice that. 

#3 The reconnect: It doesn' do all the commands needed to configure the session as it was originally set. Compare the normal connect to the reconnect sequence please to help find this. A missing command? Perhaps a SITE command that you do on a regular connect (at the beginning) is not being replicated on an automatic reconnect?

So,
#1 I will check that one
#2 Let's leave that one for the last - but it is causing the reconnect, which causes/shows up #3
#3 Can you investigate? Or I need a log that shows the initial connect to the server

**Comment by FanDjango** [comment]
Re. #1: ObjectInfo failure message: I knew it. I remember dimly having visited that dungeon sometime in the past. And then I see in your log, FluentFTP 47.1.0.0(.NET Standard 2.1). 
Look:
![image](https://github.com/robinrodricks/FluentFTP/assets/51046875/2c171feb-7dd5-4fda-8c30-0f60871e9f98)

That fix is in 48.0.0 onwards.

**Comment by FanDjango** [comment]
Re. #2: Also in 48.0.0:
![image](https://github.com/robinrodricks/FluentFTP/assets/51046875/bf37db08-f39e-4103-9896-e5b3acbc8bbb)

**Comment by FanDjango** [comment]
So, re. #1 and #2: I don't really want to spend more time on analyzing old logs, can we agree on that? I am not saying that the above two fixes can't have any mistakes, but we should be working on the basis of the current code, ok?

> We use the library in the FTP connector there. We have a customer who faces the error File must be specified by library/file.member regularly in different operations.
The customer had an older version earlier 35.2.2 and the issue wasn't happening there. Also upon further investigaton, we noticed this only happens when we use OpenRead() on the same connection and we also see some stale data in the logs, so probably has something to do with OpenRead and stale connections

I think we have been able to explain most of the statements in your OP, and that there are such a large combination of single separate issues in there that all contribute, like an onion.

Of course I did see:

>Tried with 47.1.0/48.0.3 (same behaviour on both)

but put yourself in my place: Which version would you prefer to see and analyze the logs from?

> The customer had an older version earlier 35.2.2 and the issue wasn't happening there.

You mean, there was no problem at all, none whatsoever? In that case, yes, we definetly need to continue researching this to the bitter end, and get to the bottom of each and every separate problem.

The logic behind these issues is interesting, if you look at the failures: Because of the obsolete OpenRead, we get stale data, then we get a reconnect because of that, which causes a loss of the NAMEFMT 1. Onion. But I would like all three of these to be fixed.

**Comment by anandgmenon** [comment]
Thanks a lot for you explanation. 

>As I said, in those days OpenRead probably did a GetReply, before being declared obsolete? But if that were the case, you would have seen the 501 message. I rather think that the 501 message was not being retrieved at all.

The 501 error was getting bubbled up regardless of whether we were using GetReply actually. Infact if you see the title of the issue, I actually mentioned that even before we fixed the OpenRead.

For #3:
> Solution 1: Avoid the reconnect. But as you can see, a reconnect is quite a useful recovery. Otherwise you would need to query and detect connection status and connect again yourself. I wonder if you do it yourself, whether you would also "lose" the NAMEFMT setting?

I don't think we do any reconnects on our end. Isn't it the FluentFTP library itself which tries to reconnect here? From our end, we just attempt to connect once, and maintain the connection till its valid (by checking IsConnected & IsStillConnected), otherwise we dispose it.

> Solution 2 and experiment: Do a "Execute("SITE NAMEFMT 1") after the connect yourself. Not a solution, because it won't be done on a reconnect. First, I would like to know what would be the answer to a "SITE NAMEFMT 1"? Then we maybe would code a custom server handler.

How can I do this? Is there a handle for reconnects somehow?

For #1 and #2, yes it totally makes sense to try with the latest version. I am attaching the latest logs of 3 clients which had the issue. Like you mentioned the issue seems to be reconnects not doing a `NAMEFMT` somehow. But please do check and see if you find anything interesting there. 
[client 1](https://github.com/robinrodricks/FluentFTP/files/13807573/logs3.txt)
[client 2](https://github.com/robinrodricks/FluentFTP/files/13807574/logs4.txt)
[client 3](https://github.com/robinrodricks/FluentFTP/files/13807575/logs5.txt)

**Comment by FanDjango** [comment]
Thank you for these very interesting logs.

Some tips and then we can collaborate on analyzing the multiple findings:

1. It is very useful to do a search on the string "connect(true)" to locate all re-connects.
2. It is essential to look at each occurrence of "LIST /E920/PY920/Export/Concur" and to check up on how it fared.

One think that I notice is: Sometimes the "LIST /E920/PY920/Export/Concur" works, and sometimes is does not. Each time, we need to guess why it does not.

And then we need to develop a strategy on how to improve the behaviour.

Client 1:
Fresh connect
LIST /E920/PY920/Export/Concur (from GetObjInfo)
Immediate **FAIL**, no 501 message, no nothing
reconnect due to fail
redo LIST /E920/PY920/Export/Concur
501 error msg
**FAIL**


Client 2:
Fresh connect
LIST /E920/PY920/Export/Concur (from GetListing)
Received 125-NAMEFMT set to 1, 125 LIST started
Got list, then got 250 List Completed

Further list commands also ok.

Then reconnect triggered by:
Warning:  Reconnect needed due to max SslSessionLength reached on control connection (SslSessionLength: 753)

After that, LIST and filename produce the 501 error msg


Client 3:
Same as client 2.

Now a theory from me:

Are you using the **same** userid for each client? And they run parallel? 

I think there is a script or config on the server that will automatically set NAMEFMT to 1, on the first command needing a filename,  that is issued to the server, and that is stored(remembered) for the user for that session, is is that setting shared between sessions, because it is the same user? Or, when connecting afresh, maybe the NAMEFMT will be set to 1 only if you wait a short while before reconnecting. There is something happening here what **we do not quite understand** yet.

> I don't think we do any reconnects on our end. Isn't it the FluentFTP library itself which tries to reconnect here?

Yes. It is so. But still you can try to avoid...

**Immediate **FAIL**, no 501 message, no nothing**

This is a fresh connect - that proves that there is something fishy going on, still. No idea yet where this one comes from. Seems like the server log could tell us something.

**Reconnect needed due to max SslSessionLength reached on control connection (SslSessionLength: 753)**

You can turn that feature off. Set the max session length to zero and see if that helps. I don't really think it will, because we needed to put that in as .NET SslStream likes to abort after long sessions due to some internal overruns.

What YOU could do, is to terminate sessions yourself after, say, an hour or so. And wait 5 minutes before re-establishing them. See if things get better. See if that wait resets the NAMEFMT logic of the server

> How can I do this? Is there a handle for reconnects somehow?

We don't currently plan an option to diable automatic reconnects at this time.

> yes it totally makes sense to try with the latest version

Thanks for these logs - they show the actual problems still left over.

#1: The client #1 failure (**why**)? -> reconnect -> NAMEFMT **not** set
#2: MaxSslSessionLength exceeded -> reconnect -> NAMEFMT **not** set
#3: Strange NAMEFMT behaviour by the server (**WHY**)

**Comment by FanDjango** [comment]
For me, this boils down to: **SITE NAMEFMT 1** is not in effect in some circumstances, why?

You could do, as I said, an explicit "`Execute("SITE NAMEFMT 1)`" in front of all important commands. See how the server reacts to that.

**Comment by FanDjango** [comment]
One other possible solution comes to mind:

FTP is not really meant to cater for (multiple) endless sessions being kept alive. There is no huge performance loss to be afraid of by terminating the sessions after your 1 minute check interval and logging on again cleanly at the next check. You would avoid a mutlitude of potential problems by taking that approach instead of keeping the sessions alive.

**Comment by FanDjango** [comment]
As the server welcome message has been modified and is no longer standard, 
```
Message: Response: 220-E1ENT02
Message: Response: 220 Connection will close if idle more than 5 minutes. [738875.572d]
```
the AS/400 is not being recognized - so a server handler for this system is not being set.

This has no effect right now, as the server handler for AS/400 currently does not contain any special actions anyway.
```
Message: Command:  SYST
Message: Status:   Waiting for response to: SYST
Message: Response: 215  OS/400 is the remote operating system. The TCP/IP version is ""V7R3M0"". [38ms]"
Message: Status:   Active ServerHandler is: None
Message: Status:   Listing parser set to: IBMOS400
```

But, I am coding a special action right now, which will set "LISTFMT 1" and "NAMEFMT 1" on the server right after connecting automatically. To make this special action wotk, I am coding a recognition of the SYST reply to be active - thus setting the server handler and enabling these setup commands to be issued.

I will commit this change right now and I would appreciate your looking into using that, perhaps - it should maybe be another avenue to get your connections to that server to work better.

**Comment by anandgmenon** [comment]
Sure, I'll come back with trying couple of scenarios suggested by you:
- Explicitly calling `Execute("SITE NAMEFMT 1)` before any command.
- Using the latest master to see  if #1442 improves the connections

**Comment by anandgmenon** [comment]
@FanDjango, sorry for the delay, was waiting for response from the customer.

As mentioned earlier, please see the logs for both scenarios mentioned above
- Explicitly calling Execute("SITE NAMEFMT 1) before any command: [logs-namefmt.txt](https://github.com/robinrodricks/FluentFTP/files/14051816/logs-namefmt.txt)
- Logs with latest master: 
[logs-latest.txt](https://github.com/robinrodricks/FluentFTP/files/14051963/logs-latest.txt)

Please do take a look and check if you find something.

Couple of questions:

- I know you mentioned this before, but we do see `Warning:  Reconnect needed due to max SslSessionLength reached on control connection (SslSessionLength: 751)` this warnings and which is causing the reconnects. Should we try turning it off and see if that fixes the issue here?
- It was working on 35.2.2 version for the customer. I am aware that there were a lot of changes after that. But do you think if something has changed wrt reconnects and NAMEFMT after that?

**Comment by FanDjango** [comment]
> Explicitly calling Execute("SITE NAMEFMT 1) before any command

I can see in the log, that the NAMEFMT command is not actually included in front of **every** command that uses a file name. You must have missed a few places. So, as was bound to happen, a reconnect happened **just** as a `STOR` was to be done. I guess it is difficult to actually achieve that, and it is a lot of unneeded commands and overhead, perhaps we should cross this possible solution from the list.

> latest master

I looked at the connect messages and was disappointed - there were no serverhandler init commands (`SITE NAMEFMT 1`) to be seen, what went wrong? I then checked the code of the latest master and saw that I had only coded this for SYNC, not for ASYNC connect. Duh, my bad. Your code is very probably ASYNC, am I right? I have fixed and committed this right away and it is worth testing this again IMO. #1385. Mea culpa 

> It was working on 35.2.2 version for the customer

There were no reconnects then. Perhaps that explains it?

> Should we try turning it off and see if that fixes the issue here?

This is worth a try, certainly. Note that the automatic reconnect feature was introduced to handle those SSL connections that simply "died" after about 700-1000 transactions by quitting and reconnecting. This was a very old problem that had been plagueing us, perhaps you never noticed it due to other things. So you might be exchanging a currently solvable problem (we are getting on the right track, step by step) by a different one that is more troublesome, because it is difficult to handle.

I'd rather get the NAMEFMT to be set reliably on the reconnect.

**Comment by anandgmenon** [comment]
> Your code is very probably ASYNC, am I right? I have fixed and committed this right away and it is worth testing this again IMO. https://github.com/robinrodricks/FluentFTP/issues/1385. Mea culpa

Oh yes, we mostly rely on ASYNC operations. I'll get the logs from the latest master in that case.

> There were no reconnects then. Perhaps that explains it?

So the connections just died then and we propagated it to the client?

> I'd rather get the NAMEFMT to be set reliably on the reconnect.

Yep makes sense, and just to confirm, this is what we added in the latest commit right?

**Comment by FanDjango** [comment]
> I'd rather get the NAMEFMT to be set reliably on the reconnect.

> this is what we added in the latest commit right?
> I'll try the latest master in that case.

Actually, it has even been released two days ago. https://www.nuget.org/packages/FluentFTP/49.0.2

Anyway, that is the code base we should base further analysis and testing on. I believe that barring any  other new surprises, we should be getting a clean log now.

Concerning the forced re-connects:

Since such a reconnect might come at a time that is inopportune, you could avoid these not by turning the feature off, but by terminating/reconnecting the individual clients of yours yourself, after a safe number of cycles, after any transfer is completed. You nearly have the needed logic in place already anyway. This would avoid a recconect happening in the middle of some application logic that you don't want to be interrupted.

> we propagated it to the client?

I cannot say. Would that not depend very much on how the application code reacts to such failures, perhaps the files were transmitted on the next time slot. I don't know.

**Comment by anandgmenon** [comment]
Sorry for the delayed response. But good news is after trying the newer version the issue doesn't seem to happen anymore. So I can confirm that the fix is working and we are good to close this issue :)
