### ISSUE TITLE
Unit Tests and AppVeyor

### ISSUE THREAD

**Issue by stevebpdx** [robinrodricks/FluentFTP#158]
Any plans to create actual unit tests using a testing framework?

**Comment by hgupta9** [comment]
Do you have any idea how this could be done? We may have to monitor the response code for each command sent.. Also we will need a public FTP server (I cannot contribute that, sorry) that we can use in the testing. Also there are different server types which have different command support, ie. Windows Server, Unix-based, IBM, VMS), how would we run tests for all/some of these?

**Comment by artiomchi** [comment]
The tests project is a bit of a mess, tbh, but I've started to do some cleanup for it. I have a working CI for the project already, and I'm converting the Tests project to use xUnit, where the synthetic tests are working already. 

At this point we'd just need some test servers to be able to actually test it :)

**Comment by robinrodricks** [comment]
Let's see maybe I can contribute those since you have done so much to make this work..

**Comment by robinrodricks** [comment]
@artiomchi Created the AppVeyor account and added a project for FluentFTP. What now?

Ref : https://ci.appveyor.com/project/RobinRodricks/fluentftp/

**Comment by artiomchi** [comment]
That's all you need. If you check the commits page, you can see that each commit is now built in AppVeyor (thanks to the `appveyor.yml` file, which has the build configuration), and runs unit tests after the build.

You can also see whether the build was successful or not.

Each pull request will also have a status displayed from AppVeyor, so that you will know whether a specific PR will bring any compilation errors or fail some of the unit tests.

**Comment by robinrodricks** [comment]
Great!
