### ISSUE TITLE
Inconsistency of throw exception while using 

### ISSUE THREAD

**Issue by vancodocton** [robinrodricks/FluentFTP#1664]
**FTP Server OS: Unix

**FTP Server Type: Vsftpd

**Client Computer OS: Windows

**FluentFTP Version: 51.1.0

**Framework:** .NET 8

I use `AsyncFtpClient` to download and upload file. In the case that file does not exist:
* `DownloadFile` throw `FtpMissingObjectException` with inner exception `FtpCommandException`
* `DeleteFile` throw `FtpCommandException`.

That lead to catching exception is frustrating. Hope you can fix it asap

**Comment by FanDjango** [comment]
You are referring to

```cs
			if (!(reply = await Execute("DELE " + path, token)).Success) {
				throw new FtpCommandException(reply);
```
which is executed when you do a `DeleteFile(...)`.

Since there are more possible reasons for a DELE command to fail (for example: permissions), the general description would be a "CommandException". You should actually, when doing a DeleteFile, check why it failed.

While it would be possible to introduce a check for the message texts associated with a missing file, similarly to the way Upload/DownloadFile does this, this is an effort that is not a high priority given our current workload.

If you look at the implentation of recognizing a MissingObjectException:

```cs
		/// <summary>
		/// Error messages returned by various servers when a file does not exist.
		/// Instead of throwing an error, we use these to detect and handle the file detection properly.
		/// MUST BE LOWER CASE!
		/// </summary>
		public static string[] fileNotFound = new[] {
			"can't find file",
			"can't check for file existence",
			"does not exist",
			"failed to open file",
			"not found",
			"no such file",
			"cannot find the file",
			"cannot find",
			"can't get file",
			"could not get file",
			"could not get file size",
			"cannot get file",
			"not a regular file",
			"file unavailable",
			"file is unavailable",
			"file not unavailable",
			"file is not available",
			"no files found",
			"no file found",
			"datei oder verzeichnis nicht gefunden",
			"can't find the path",
			"cannot find the path",
			"could not find the path",
			"file doesnot exist",
			"couldn't open the file or directory"
		};
```
you will notice that the list is potentially endless, server specific and prone to spelling mistakes, missing languages etc.

Thus it would be preferrable to make ´FtpCommandException` the common denominator - probably causing a lot of pain for those users who rely on this historically.

I would prefer to do **nothing** about this for now. If you want to, you can supply a PR to remedy this yourself in a suitable fashion (with the emphasis on **suitable**) and I can assure it will be reviewed graciously.
