### ISSUE TITLE
Infinite cycle in ReadStaleData on Dispose

### ISSUE THREAD

**Issue by sherlock1982** [robinrodricks/FluentFTP#1676]
**FTP Server OS:** Unknown

**FTP Server Type:** Unknown

**Client Computer OS:** Debian

**FluentFTP Version:** 51.0.0

**Framework:** .NET 8

Sometimes we have the following stacktrace that never ends on Dispose of FTP client:
```
00007F7C5F7E59B8 00007fbdd421dc5b [InlinedCallFrame: 00007f7c5f7e59b8] Interop+Sys.<GetBytesAvailable>g____PInvoke|13_0(IntPtr, Int32*)
00007F7C5F7E59B8 00007fbd63542fb9 [InlinedCallFrame: 00007f7c5f7e59b8] Interop+Sys.<GetBytesAvailable>g____PInvoke|13_0(IntPtr, Int32*)
00007F7C5F7E59A0 00007FBD63542FB9 Interop+Sys.GetBytesAvailable(System.Runtime.InteropServices.SafeHandle, Int32*) [/_/src/libraries/System.Net.Sockets/src/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs @ 400]
00007F7C5F7E5A40 00007FBD63542DDA System.Net.Sockets.Socket.get_Available() [/_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs @ 271]
00007F7C5F7E5A80 00007FBD6397CD43 FluentFTP.Client.BaseClient.BaseFtpClient.ReadStaleData(System.String)
00007F7C5F7E5AC0 00007FBD63962982 FluentFTP.Client.BaseClient.BaseFtpClient.FluentFTP.IInternalFtpClient.ExecuteInternal(System.String)
00007F7C5F7E5B80 00007FBD6399E9C6 FluentFTP.FtpClient.Disconnect()
00007F7C5F7E5C10 00007FBD6399E8FC FluentFTP.Client.BaseClient.BaseFtpClient.FluentFTP.IInternalFtpClient.DisconnectInternal()
00007F7C5F7E5C40 00007FBD6399E7FB FluentFTP.Client.BaseClient.BaseFtpClient.Dispose()
```

This happens on sending the last "QUIT" command.

From our research it happens here:

				if (Status.IgnoreStaleData) {
					Stopwatch sw = new Stopwatch();
					sw.Start();

					LogWithPrefix(FtpTraceLevel.Verbose, "Stale data wait - " + logFrom);

					do {
						if (m_stream.SocketDataAvailable > 0 || !m_stream.IsConnected) {
							break;
						}
					} while (true);

					if (m_stream.IsConnected) {
						LogWithPrefix(FtpTraceLevel.Verbose, "Stale data took " + sw.ElapsedMilliseconds + "(ms) to arrive");
					}
				}

I have two notes on this cycle.

1. There's no sleep inside. Meaning it will take 100% of CPU
2. What is the purpose of it? What if it never finishes? And this is exactly what we see randomly.

I will try to provide more logs once we reproduce with verbose logging but in general it doesn't look good to me already

**Comment by FanDjango** [comment]
First of all, thanks for reporting this.

> but in general it doesn't look good to me already

Yup, it sure doesn't.

> What if it never finishes?

It should finish. But here we again have an edge case where sockets, the IP stack and intermediate implementations leave room for "glitches". 

> What is the purpose of it? 

In some cases stale data **is actually to be expected** and this code is meant to **wait** for the data to arrive - or to break the wait until the connection is no longer connected.

Somebody goofed by writing a tight loop, there is no wait in there. That somebody was me.

And if the logic that sets `IsConnected` does not actually set this - which for example can happen in some configurations (if you want details, please ask) - when a connection goes down, this is a cpu loop.

Interestingly, this has never been reported and so it has gone unnoticed since (actually) quite some time.

And now it is time to fix this: 

1. By introducing a sleep to make the loop less intensive
2. By introducing a maximum elapsed time the loop may exist and to somehow recover in that case.

No need to produce more elaborate logs, unless you feel that you can identify **common and specific** situations where this actually happens - you did mention "when the FTP client is disposed".

Note that from your FluentFTP version V51.0.0, looking at the current master on GitHub, there have been some changes in the dispose logic also, so perhaps it might be nice to catch this on the latest and greatest, it at all possible.

**Comment by FanDjango** [comment]
By the way: Do you have any new feedback on #1536?

**Comment by FanDjango** [comment]
Just try it, please.

**Comment by sherlock1982** [comment]
Ok I can confirm the issue is not reproduced anymore (built from sources). Can you please publish it?

**Comment by FanDjango** [comment]
Releases to Nuget, et. publishing is the realm of @robinrodricks and it happens at his discretion.

**Comment by FanDjango** [comment]
Closed - there will be a notify on Nuget release
