### ISSUE TITLE
Default connection type should not be enhanced active/passive

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#215]
> I've noticed that enhanced active and passive mode don't work quite so well with some FTP servers. The reason FileZilla can work with them because it doesn't seem to use it, and instead uses regular passive mode. - @artiomchi

We need to see how to make regular passive and active modes the default / recommended option instead of enhanced, to be more similar to FileZilla and reduce the number of out-of-the-box issues.

**Comment by artiomchi** [comment]
I was thinking about that, and I was wondering if there's an issue with the enhanced implementations.

Even if the issue is on the server side, it would be cool if the library could fall back to regular modes in case of known errors.

To do this, the best thing to do is get some test servers and run some experiments.

I'm planning to spin up several different ftp servers soon, but I don't have a time estimate just yet on that

**Comment by robinrodricks** [comment]
Fixed when using **AutoDetect()** in 26.0.1.

We now select protocols in this order of preference:
- FtpDataConnectionType.PASV (passive)
- FtpDataConnectionType.EPSV (enhanced passive)
- FtpDataConnectionType.PORT (active)
- FtpDataConnectionType.EPRT (enhanced active)
- FtpDataConnectionType.PASVEX
