### ISSUE TITLE
Use Project in older Visual Studio Versions (2012 here)

### ISSUE THREAD

**Issue by The-Abc** [robinrodricks/FluentFTP#235]
I am using VS 2012 Professional.

How can use this project?
I edited the csproj File manually, but there are so much more problems...

kind regards,
The-abc

**Comment by robinrodricks** [comment]
Hi. A few months ago we were using VS 2012 but a contributor updated it to use VS 2017 since we are targeting .net core which is only possible in the new VS. Why can't you use the new VS? It's free if you use the community version. If you really really need to build it then refer to this older version of FluentFTP for the projects and copy the code files from the latest trunk. 

The last revision that used VS 2012 : a900270ba76f15778c733733305be0e9f3dd66c5

**Comment by robinrodricks** [comment]
Link : https://github.com/robinrodricks/FluentFTP/tree/a900270ba76f15778c733733305be0e9f3dd66c5

**Comment by robinrodricks** [comment]
Closing this as I have answered your question. If you need any more help, add a comment.
