### ISSUE TITLE
Unroutable address for passive mode

### ISSUE THREAD

**Issue by elmar69** [robinrodricks/FluentFTP#270]
FTP Server: ProFTPD 1.3.5

I'm not shure about this really beeing an bug but filezilla does handle the Problem.
On Opening an passive connection the server does respond
"227 Entering Passive Mode (192,168,178,2,246,61)."
This raises the problem that trying to connect does timeout since the mentioned IP address is an unrouted private one.

Filezilla in this case does ignore the IP mentioned and does connect to the host IP after printing an warning.

It is an misconfiguration of the server but I would estimate it to happen often if filezilla does implement an explicit workaround to that.

**Comment by martinvonwittich** [comment]
The problem in this situation is that ProFTPd doesn't know its own public IP address (because it is situated behind a NAT router), but the FTP spec forces the server to respond to `PASV` with both the IP address and the port. ProFTPd will respond with the IP address from the network interface where it originally received the FTP connection, which would be fine if this interface was directly connected to the Internet (then the interface would have the public IP), but in this case the interface has the private IP address 192.168.178.2.

In the past (with unencrypted connections) this problem was alleviated by the fact that NAT routers usually simply rewrite the PASV response and replace the private IP with the correct public IP, but this no longer works in a modern setup where encryption is enforced because due to the encryption, the router can neither see nor rewrite the PASV response.

A possible workaround on the server side would be to use the [MasqueradeAddress](http://www.proftpd.org/docs/directives/linked/config_ref_MasqueradeAddress.html) option to tell ProFTPd the correct public IP address. Unfortunately the typical use case for NAT routers are residential DSL connections with dynamic IPs that change every 24 hours, which makes this workaround complicated to set up because it would require a script that monitors the public IP, automatically updates the ProFTPd configuration and then restarts it.

A better solution is to use the more modern `EPSV` command specified by [RFC2428](https://tools.ietf.org/html/rfc2428) on the client side. The `EPSV` response will only contain the port and no IP address, and the client is then supposed to connect to the same IP address as for the control connection.

**Comment by robinrodricks** [comment]
We had a fix for this in [22](https://github.com/robinrodricks/FluentFTP/blob/master/RELEASES.md#2200). Can you download the latest via nuget and see if it works?

**Comment by robinrodricks** [comment]
I'll reopen this if you still get errors.
