### ISSUE TITLE
Access Denied on upload

### ISSUE THREAD

**Issue by rskuchenbrod** [robinrodricks/FluentFTP#324]
I"m receiving an Access denied when trying to put a file on the FTP Site. Looking at the inner exception I have noticed it is on the delete function in fluentFTP. 

(FluentFTP.FtpCommandException: Access is denied. at FluentFTP.FtpClient.DeleteFile(String path) at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)) 

I have tried using filezilla manually and have success there. I"m not sure how to generate a Log in FleuntFTP or I would also provide that in the Message, Any help  would be grateful

RSK

**Comment by robinrodricks** [comment]
Unless we have the logs we cant debug. Sorry. Check FAQ for providing logs.

**Comment by wylanosorio** [comment]
Updating target folder's security settings to allow users to "Write" solved for me.

**Comment by wjchristenson2** [comment]
I had the same issue with client.Upload(). Using CuteFTP and .NET's FtpWebRequest I could delete files no problem. Then tried explicitly just doing a client.DeleteFile() with FluentFTP and got the same error "Access Denied". Then tried (with FluentFTP) uploading a brand new file (success) then immediately deleting it (success).

After further analysis of upload then a delete success, I discovered that if files on the FTP server do not have an explicit security permission for the FTP user that FluentFTP's client is using, it doesn't work despite the fact that the user is a member of a group that has write permissions to the entire folder and files within. When you upload a new file with FluentFTP, a security permission is explicitly created for the user on the file. That's why you can subsequently delete the file. We are using IIS to host the FTP site. Reverting code back to .NET's FtpWebRequest to get around this for now.

@robinrodricks any thoughts on a setting to change the client's behavior?
