### ISSUE TITLE
Output stream buffer size

### ISSUE THREAD

**Issue by 3x0dv5** [robinrodricks/FluentFTP#471]
This 4096, is there a way we could have it as a property or a parameter?
https://github.com/robinrodricks/FluentFTP/blob/c4989d69a72d161350fbcf554f727da442dac1cd/FluentFTP/Client/FtpClient_HighLevelDownload.cs#L438

FluentFTP is much slower than Filezilla when writing on to a mapped drive although is slightly the same when writing to a local drive, trying to figure out if by increasing this buffer size we can get better performance when writing to a mapped drive.

**Comment by robinrodricks** [comment]
First try changing it and build from source. If it works we can definitely
add a property.

**Comment by cgbhub** [comment]
I downloaded 32.4.0 and updated both occurrences to a much larger buffer size.  When transferring a file from IBMzOSFTP to Mapped drive, the speed greatly improved.  For one of my small sample files went from 1 minute down to 20 seconds.  The download timings now closer resemble the upload timings.

I bumped my buffer to be twice the chunksize (probably over kill), however if this can be made available by a property, then users can properly size it based upon their need.

FtpFileStream.cs
 return new FileStream(localPath, FileMode.Create, FileAccess.Write, FileShare.None, **4096**, isAsync);

Thank you,
This is a great product.  The only negative feedback I have heard was the download speed to a server.

**Comment by robinrodricks** [comment]
Oh that's great. Thanks so much for testing and confirming.

Apart from adding a parameter, should we change the default value as well or set a default based on the server? And is your server IBM z/OS?

**Comment by cgbhub** [comment]
our ftp server is the ibm/os.  Only point on that is it is an unknown file size so that memory buffer is not used.  it is being downloaded to an windows server thru a mapped drive.  Thats where the buffer change is needed.buffer size default recommendations are hard because it depends on your environment.   I would keep the default as is and let the users optimize to their usage.  Similar to the chunksize you have.Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: TheFlash <notifications@github.com> Date: 5/13/20  8:46 AM  (GMT-05:00) To: robinrodricks/FluentFTP <FluentFTP@noreply.github.com> Cc: cgbhub <blenkerchris@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [robinrodricks/FluentFTP] Output stream buffer size (#471) 
Oh that's great. Thanks so much for testing and confirming.
Apart from adding a parameter, should we change the default value as well or set a default based on the server? And is your server IBM z/OS?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/robinrodricks/FluentFTP/issues/471#issuecomment-627958870",
"url": "https://github.com/robinrodricks/FluentFTP/issues/471#issuecomment-627958870",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by robinrodricks** [comment]
Great. Should there be one property like `TransferFileBufferSize` or 2 properties like `UploadFileBufferSize` and `DownloadFileBufferSize`

**Comment by cgbhub** [comment]
I can go with the single property or both.  I don't think we would use the file stream on a read and write at the same time, so a single property may be less confusing to users.  It will apply to the upload (read) or the download (write). I don't think read is much an an issue compared to write since data can be prefetched by the operating system on a read.if I'm reading the code correctly, what you are proposing is the Filestream with the FileAccess.Read will use UploadFileBufferSize and the ones with FileAccess.Write will use DownloadFileBufferSize.And the current chunkFileSize is the communication to the ftp server.Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: TheFlash <notifications@github.com> Date: 5/13/20  2:06 PM  (GMT-05:00) To: robinrodricks/FluentFTP <FluentFTP@noreply.github.com> Cc: cgbhub <blenkerchris@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [robinrodricks/FluentFTP] Output stream buffer size (#471) 
Great. Should there be one property like TransferFileBufferSize or 2 properties like UploadFileBufferSize and DownloadFileBufferSize

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/robinrodricks/FluentFTP/issues/471#issuecomment-628156042",
"url": "https://github.com/robinrodricks/FluentFTP/issues/471#issuecomment-628156042",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by robinrodricks** [comment]
Ok great I'll just add one property and we can take it from there.

**Comment by robinrodricks** [comment]
Released.

#### 32.4.1
  - New: `LocalFileBufferSize` property to control size of file buffer during local file I/O
