### ISSUE TITLE
How often are NuGet packages pushed? Request for folder download functionality

### ISSUE THREAD

**Issue by ntindle** [robinrodricks/FluentFTP#515]
I see that Folder Download has been added to the client in master and was wondering what the propagation to nuget time is

**Comment by robinrodricks** [comment]
Good point! It was developed yesterday as part of a long term enhancement that came up quite often as a feature request. As its in beta, are you willing to test it before I release it?

**Comment by robinrodricks** [comment]
Usage docs : https://github.com/robinrodricks/FluentFTP#directory-transfer

**Comment by ntindle** [comment]
I sadly would be unable to beta test it as part of any software. I don’t have servers that are available for beta testing :/

**Comment by robinrodricks** [comment]
Go!

https://www.nuget.org/packages/FluentFTP/30.0.0

  - New: `UploadDirectory` and `UploadDirectoryAsync` methods to recursively upload or mirror a directory
  - New: `DownloadDirectory` and `DownloadDirectoryAsync` methods to recursively download or mirror a directory
  - New: Rule engine to filter files that should be uploaded/downloaded according to multiple user-defined rules
  - New: Predefined rules for filtering on folder name, useful for blacklisting certain system folders
  - New: Predefined rules for filtering on file name or file extensions, useful for transferring a subset of files
  - New: Predefined rules for filtering on file size, useful for filtering out very large files
  - New: Ability to determine parent/self/child directories in listing using `SubType` property of `FtpListItem`
  - Fix: Machine listings sometimes cause infinite recursion in `GetListing` when recursing into self directory
  - Change: `CreateDirectory` and `CreateDirectoryAsync` now return a flag indicating if it was created or skipped
  - Change: Use public fields instead of public properties for `FtpListItem`
  - Change: Improve performance of `CreateDirectory` by skipping the directory exists check
