### ISSUE TITLE
InvalidOperationException on Linux since SSL session resumption is not supported

### ISSUE THREAD

**Issue by JCPuerto** [robinrodricks/FluentFTP#519]
This is related to issue https://github.com/robinrodricks/FluentFTP/issues/347.

In the next line we're catching everything but according to the comment we should just catch `TimeoutException`. Otherwise we ignore the `InvalidOperationException` thrown by the related issue https://github.com/robinrodricks/FluentFTP/issues/347.
https://github.com/robinrodricks/FluentFTP/blob/ce071ffa08532a23a3090b58b9de34daa7608927/FluentFTP/Client/FtpClient_FileUpload.cs#L821

Since issue https://github.com/robinrodricks/FluentFTP/issues/347 causes an empty file on the server this behavior won't change but at least we will know the upload failed. I wasn't getting exceptions and I though everything was going fine.

**Comment by robinrodricks** [comment]
That is meant to catch stray exceptions that occur after the file has uploaded. Maybe we can filter out InvalidOperation and re-throw it? But then it would risk breaking production code for other users. Why do you need to know this InvalidOperationException?

**Comment by robinrodricks** [comment]
If you need to detect this error "Authentication failed because the remote party has closed the transport stream" then we can specifically detect it and throw it. Would that work?

Can you download FluentFTP project source, add to your solution, put a breakpoint at that try/catch catch statement and tell me the exact error/exception you want to catch and we can work it out?

**Comment by robinrodricks** [comment]
Related https://github.com/robinrodricks/FluentFTP/issues/509

**Comment by robinrodricks** [comment]
This has been fixed. If you still get the error let me know and we can reopen this issue.
