### ISSUE TITLE
Matching files, UploadFile() and DownloadFile() return different values

### ISSUE THREAD

**Issue by inside686** [robinrodricks/FluentFTP#524]
Windows
FileZilla
Windows 10
v30.2.0

There is a difference of logic between DownloadFile() and UploadFile() method when a matching file already exists in the destination (and either Append or Skip ExistsMode are used).
In case of match, UploadFile() returns True however DownloadFile() return False.
Can the behavior be aligned for both methods?

[FluentFTPException_20200212_161315.txt](https://github.com/robinrodricks/FluentFTP/files/4193390/FluentFTPException_20200212_161315.txt)

**Comment by robinrodricks** [comment]
Good idea. Will fix and let you know.

**Comment by robinrodricks** [comment]
Done.

https://www.nuget.org/packages/FluentFTP/31.0.0

#### 31.0.0

  - New: Download and upload file methods indicate if file was transferred, skipped or failed to transfer
  - New: C# and VB.NET Examples for all file and folder transfer methods
  - New: VB.NET Examples for all methods (not included in Nuget package but available on Github)
  - Change: `DownloadFile` and `UploadFile` return `FtpStatus` instead of boolean flag for tri-state feedback
