### ISSUE TITLE
GetListing() returns a NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by fredrikhaglund** [robinrodricks/FluentFTP#592]
**FTP OS:** Unix 

**FTP Server:** Unknown

**Computer OS:** Windows 10, Version 2004 19041, .NET Core 3.1.5

**FluentFTP Version:** 32.4.3

**GetListing()** returns **NullReferenceException** that probably hides a TLS-issue since the problem disappearswith **DataConnectionEncryption = false**. 

Same issue as #589 that is closed with the conclusion that using *FtpListOption.UseStat* will solve the problem. STAT will not open a data channel so you will run into the issue later when you try to download a file for example.

``` csharp
var client = new FtpClient(host, port, username, password); 
client.EncryptionMode = FtpEncryptionMode.Explicit;
//client.DataConnectionEncryption = false;
client.Connect();
var list = client.GetListing();
```
**Expected:** Should return an array with items
**Actual:** GetListing() throws a NullReferenceException unless DataConnectionEncryption = false;

The NullReferenceException is thrown in [GetListingInternal() L589](https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Client/FtpClient_Listing.cs#L589) in an error handler because the CompletionCode is null. 

``` csharp
catch (FtpCommandException ftpEx) {
// Some FTP servers throw 550 for empty folders. Absorb these.
	if (!ftpEx.CompletionCode.StartsWith("550")) {
		throw ftpEx;
	}
}
```
The inner exception is thrown in [CloseDataStream L988](https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Client/FtpClient_Stream.cs#L988) when the data stream is closed because it did not return any data and all fields of the reply object are null.

It appears the data stream returns nothing when DataConnectionEncryption is true which is probably the root of the problem.

Question: How can I dig deeper to understand why the data connection encryption can not be enabled when using FluentFTP but works fine with FileZilla?

Enhancement: Error handlers should probably be improved to be null safe and give an better error when the data stream returns no data.

**Other findings :**
- Using FileZila to connect to the same server does open an encrypted data connection using TLS 1.2 without any problem.
- Trying with different TLS versions gives the same result.
- Trying with different passive DataConnectionTypes does not make any difference
- SslBuffering = FtpsBuffering.Off does not make any difference
- SocketPollInterval = 0 does not make any difference

**Logs :**

```
# Connect()
Status:   Connecting to ***:21443
Response: 220-****************************************
Response: 220-* Please do not connect to this server *
Response: 220-*   if you are not entitled to do so   *
Response: 220-****************************************
Response: 220 This is a private system - No anonymous login
Command:  AUTH TLS
Response: 234 AUTH TLS OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,2285364.
Command:  USER ***
Response: 331 User *** OK. Password required
Command:  PASS ***
Response: 230 OK. Current directory is /
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Data protection level set to "private"
Command:  FEAT
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: 211 End.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled
Command:  SYST
Response: 215 UNIX Type: L8

# GetListing(null, Auto)

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is your current location
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
Command:  EPSV
Response: 229 Extended Passive mode OK (|||50780|)
Status:   Connecting to ***:50780
Command:  MLSD /
Response: 150 Accepted data connection
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0682148.
+---------------------------------------+
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Exception thrown: 'FluentFTP.FtpCommandException' in FluentFTP.dll
Status:   Disposing FtpSocketStream...
FluentFTP.FtpCommandException.CompletionCode.**get** returned null.

```

**Comment by robinrodricks** [comment]
Wow, thanks for this great debugging.

**Comment by christiaanderidder** [comment]
We are using FluentFTP extensively and are seeing the exact same issue (and many similar issues). So far we have seen:
- NullReferenceException because CompletionCode is nulll
- FtpCommandException because replies to a command are null
- 0 byte files (when using readToEnd and reading to a stream) / Unexpected EOF (when using a file size)
- The final part of a big file timing out when reading from the socket (Fixed by disabling SSL buffering)
- Failing to parse the EPSV port because the result of the previous command is used (file size) instead of the correct port (as seen in the server logs).

After a lot of debugging all of them seem to be related to lower level NetworkStream/SllStream/socket issues. We started seeing an increase after switching to .NET core (3.1), so it might actually have to do with differences in the implementations between full framework and core.

I'd be happy to help out with any debugging efforts.

**Comment by Seabizkit** [comment]
.net 6 and i get this when downloading...

**Comment by FanDjango** [comment]
@fredrikhaglund @christiaanderidder @Seabizkit There has been some improvement to the inner logic of `GetListing()` for the cases where authentication fails for the data channel to get the listing data. Also there has been significant improvement on the verbose error logging and the internal automatic reconnect logic. If this issue is still of concern to any of you, would you please reexamine the topics you raised and indicate your results here?
