### ISSUE TITLE
NullReferenceException in GetNameListingAsync

### ISSUE THREAD

**Issue by RedwoodForest** [robinrodricks/FluentFTP#647]
**FTP OS:** Unknown

**FTP Server:** Unknown

**Computer OS:** Microsoft Windows Server 2012 R2 Standard

**FluentFTP Version:** 32.4.5
 
We encountered this NullReferenceException in production. So far it has only happened once that I am aware of. 

Unfortunately I don't have any additional information on what's causing it or how to reproduce it yet. We've added additional code to capture the FluentFTP logs in case it happens again and will update the issue if it does.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentFTP.FtpClient.<GetNameListingAsync>d__214.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[...the rest of stack trace is from inside our code and is omitted...]
```

The call we're making to the client is:
```
var files = await client.GetNameListingAsync(
    folderUrl.AbsolutePath, 
    timeoutTokenSource.Token);
```

**Logs :**

I will update this issue if/when we are able to capture them.

**Comment by robinrodricks** [comment]
If you cannot help us find the LOC that is causing it, how are we to find the NullReferenceException? The library is getting more and more complex and unfortunately such a thing cannot be fixed theoretically. That's why we have an open source release model, so you can build from source and debug/fix such issues at your leisure. I recommend that approach. Closing for now, once you find the fix or at least the offending LOC, open a new issue. Thanks.
