### ISSUE TITLE
Verify Not working - Hash command not being parsed correctly

### ISSUE THREAD

**Issue by dbman86** [robinrodricks/FluentFTP#722]
**FTP OS:** not sure - using files.com

**Computer OS:** Windows 10

**FluentFTP Version:** 34.0.0

Server is returning this value from Hash command:

[R] HASH /pathtomyfile.
[R] 213 MD5 0-170500096 3197bf4ec5fa2d441c0f50264ca52f11

however, when the GetChecksum() method parses this to create FtpHash object, it is parsing the value as 0-170500096 instead of  3197bf4ec5fa2d441c0f50264ca52f11.

Not sure if this is the authoritative standard but this indicates the value FluentFTP is taking for the hash value is really the bit rate of the file... ?
https://www.jscape.com/blog/bid/48215/New-FTP-Command-HASH-for-Requesting-Hash-of-a-File

**Comment by robinrodricks** [comment]
Please try this build.

[FluentFTP.35.0.0_BETA6.zip](https://github.com/robinrodricks/FluentFTP/files/7071196/FluentFTP.35.0.0_BETA6.zip)

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/35.0.0

**Comment by robinrodricks** [comment]
Hi @dbman86, can you try the latest build from nuget and tell me if it resolves your issue? I need feedback on this please.

**Comment by FanDjango** [comment]
Here is the **real** fix for this problem:

And see also #1287.

QUOTE from #1286
BrickFTP (files.com / Exavault.com) responds in a non - standard fashion (no filename).

Changed the regex to handle that situation.

Incidentally: The fix for https://github.com/robinrodricks/FluentFTP/issues/722 (which was never confirmed) which attempts to remove "213" from the server response as a fix is obsolete (the server response code is removed prior to the call of this function anyway) and not the real reason why https://github.com/robinrodricks/FluentFTP/issues/722 was reported. https://github.com/robinrodricks/FluentFTP/issues/722 was another, first occurrence of "missing" filename. And lo and behold, it was the same server type as the one reported here.
ENDQUOTE
