### ISSUE TITLE
Why OpenWrite and OpenRead is obsolete now?

### ISSUE THREAD

**Issue by Jaex** [robinrodricks/FluentFTP#841]
Hi, I recently updated FluentFTP library in my [project](https://github.com/ShareX/ShareX) to latest version and noticed there is two warnings in Visual Studio and CI:

![](https://jaex.getsharex.com/2022/02/devenv_1oHg477sUW.png)

I thought, fine I will just rename function to new API and use the non obsolete API. Because mainly when one API is marked as obsolete either name of the API is changed or there is better alternative to it. But in this case it suggests me to use inferior method which I don't have full control as these methods that I was using for the [past 8 years](https://jaex.getsharex.com/2022/02/chrome_BI3AbxmY3n.png).

Both `OpenWrite` and `OpenRead` methods returns stream which then I can use built in functions from my project to have control over buffer size, stop support, transfer speed calculations, transfer progress reporting, transfer speed limiting etc. So by having access to stream, we can have full control over the transfer and seamlessly integrate our already existing stream transfer methods instead of relying on what's that high level methods are using.

Because I prefer to keep warning messages empty at my IDE and CI, I have no choice but to revert to old version of FluentFTP now and keep in that version forever.

So my questions is, when there is solid working methods which we were using past 8 years, why would you mark them as obsolete and instead suggest us to use inferior method which gives us less control than current method?

**Comment by FanDjango** [comment]
See #826 and #827. @robinrodricks Discovered the hard way that **some** people are using these, for purposes of their own. Maybe "use at your own risk" is less stringent than "obsolete" :-)

**Comment by bjallemad** [comment]
For performance reasons, the high-level API are not an option for us. For example if you want to upload a large object model as json, I don't want to first create a memory stream for the json, and then upload it. I would like to write the object model directly to the ftp stream. In this case the OpenWrite is our only option!

A suggestion for an API that could actually solve this without require advanced stream/connection handling in our code would be if you could implement a function like this instead of OpenWrite:
`public async Task UploadAsync(Func<Stream, Task> uploadStreamHandler, string remotePath, FtpRemoteExists existsMode = FtpRemoteExists.Overwrite, bool createRemoteDir = false, IProgress<FtpProgress>? progress = null, CancellationToken token = default(CancellationToken))`

In this case the upload stream and the connection can still be handled internally! 

Then I could do the following in my code:
`var largeObject = CreateLargeObject();

await ftpClient.UploadAsync(async (uploadStream) => await JsonSerializer.SerializeAsync(uploadStream, largeObject), "largeobject.json");

static List<string> CreateLargeObject()
{
	var li = new List<string>();

	for(int i = 0; i < 1000000; i++)
		li.Add(new string('l', 1000));

	return li;
}`

The same pattern is also needed when downloading, since some third party libraries (for example an Excel and Csv library we are using) takes the stream as input. In those cases this function would solve the OpenRead problem for us:
`public async Task DownloadAsync(Func<Stream, Task> outStreamHandler, string remotePath, long restartPosition = 0, IProgress<FtpProgress> progress = null, CancellationToken token = default(CancellationToken))`

**Comment by robinrodricks** [comment]
This is a good idea. Yes in most cases people were using OpenRead and OpenWrite to develop their own download/upload functions and then complaining about edge cases in such things, which I'm tired of supporting.

**Comment by robinrodricks** [comment]
For this reason I used warnings and not errors, so as not to break legitimate cases like yours.

**Comment by jmajoor** [comment]
I have a streaming application and used the OpenRead method to get a stream from an ftp file (> 100 Gb). The OpenRead allowed for a full streaming solution, whereby my application could pull data from the stream and process it while streaming. What is the alternative now that this is declared obsolete (and potentially one step away of being removed).

**Comment by robinrodricks** [comment]
I understand many users are using these methods, so they will be maintained for the foreseeable future. If we do decide to remove it, the streaming application will be preserved.

**Comment by bjallemad** [comment]
I think that marking as obsolete means that the method will be removed in the next major release, that is how other package vendors do...
If you plan to maintain these methods, I don't think they should be marked as obsolete.

Do you think that you can implement the solution that I suggested above?
In that case maybe these methods can be removed in a future release?

**Comment by lighterhy** [comment]
We have a consensus that an API marked as "obsolete" should not be used anymore because it will be removed at some point in the future.

I think you may have misunderstood Stream.
A "read" operation is a "pull" mode, means input data. it must provide the caller with a stream on which the "read" operation can be performed, and vice versa. It's a convention. Because a stream can use the decorator pattern to provide data to another stream.

Your Download/DownloadAsync methods push data directly into the stream provided by the caller, making it difficult for the decorator pattern to work. For example, if I want to download data from FTP, unzip it, decrypt it, and get the final data, I can say something like this:

```
// Download.
using var ftpStream = await client.OpenReadAsync(Url.AbsolutePath, token: cancellationToken).ConfigureAwait(false);
// Decompress.
using var gzipStream = new GZipStream(ftpStream, CompressionMode.Decompress);
// And decrypt.
using var decryptStream = new CryptoStream(gzipStream, decryptor, CryptoStreamMode.Read)) ;

// Then write to file.
using var fileStream = File.OpenWrite(@"D:\file.dat");
await decryptStream.CopyToAsync(fileStream, cancellationToken).ConfigureAwait(false);
```

How to do this with Download/DownloadAsync? We can convert a read Stream to a write via Copy/CopyAsync as in the code above, but cannot do the opposite.

So to do this with Download/DownloadAsync , I'd have to buffer everything into a huge memory, or do something like writing an intermediate stream.

Another example is about progress report. See my code in UWP:

```
StorageFile file = await StorageFolder.CreateFileAsync(fileName, CreationCollisionOption.GenerateUniqueName).AsTask(cancellationToken).ConfigureAwait(false);

using var ftpStream = await client.OpenReadAsync(Url.AbsolutePath, token: cancellationToken).ConfigureAwait(false);
using IInputStream inputStream = ftpStream.AsInputStream();

using IRandomAccessStream fileStream = await file.OpenAsync(FileAccessMode.ReadWrite).AsTask(cancellationToken).ConfigureAwait(false);
IAsyncOperationWithProgress<ulong, ulong> progress = await RandomAccessStream.CopyAndCloseAsync(inputStream, fileStream);
progress.Progress += (asyncInfo, progress) => ReportProgress(progress);
await progress.AsTask().ConfigureAwait(false);
```

So as you see, OpenRead and OpenWrite is very important for Stream decoration. Please bring it back.

Please forgive me if I have offended anything with my words. My English is poor.

**Comment by robinrodricks** [comment]
https://www.nuget.org/packages/FluentFTP/37.0.3

#### 37.0.3
 - Change: Remove `Obsolete` from all `OpenRead`/`OpenWrite`/`OpenAppend` API as it is not planned for deletion
