### ISSUE TITLE
List of server-specific SITE commands

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#88]
## DrFTPD

Commands listed [here](http://drftpd.org/index.php/Site_Commands):

- [ ] 1.1 SITE ADDIP
- [ ] 1.2 SITE ADDSLAVE
- [ ] 1.3 SITE ADDUSER
- [ ] 1.4 SITE BAN
- [ ] 1.5 SITE BLOWFISH
- [ ] 1.6 SITE CHANGE
	 - [ ] 1.6.1 SITE CHANGE wkly_allotment
	 - [ ] 1.6.2 SITE CHANGE group
	 - [ ] 1.6.3 SITE CHANGE group_slots
	 - [ ] 1.6.4 SITE CHANGE num_logins
	 - [ ] 1.6.5 SITE CHANGE ratio
	 - [ ] 1.6.6 SITE CHANGE credits
	 - [ ] 1.6.7 SITE CHANGE max_sim
- [ ] 1.7 SITE CHGRP
- [ ] 1.8 SITE CHOWN
- [ ] 1.9 SITE CHPASS
- [ ] 1.10 SITE DELIP
- [ ] 1.11 SITE DELSLAVE
- [ ] 1.12 SITE DELUSER
- [ ] 1.13 SITE FIND
- [ ] 1.14 SITE GADDUSER
- [ ] 1.15 SITE GINFO
- [ ] 1.16 SITE GIVE
- [ ] 1.17 SITE GROUPS
- [ ] 1.18 SITE IRC connect
- [ ] 1.19 SITE IRC disconnect
- [ ] 1.20 SITE IRC reconnect
- [ ] 1.21 SITE INVITE irc
- [ ] 1.22 SITE KICK
- [ ] 1.23 SITE KICK <all/*>
- [ ] 1.24 SITE LIST
- [ ] 1.25 SITE LINK
- [ ] 1.26 SITE LOADPLUGIN
- [ ] 1.27 SITE NUKE
- [ ] 1.28 SITE NUKES
- [ ] 1.29 SITE PASSWD
- [ ] 1.30 SITE PLUGINS
- [ ] 1.31 SITE PRE
- [ ] 1.32 SITE PURGE
- [ ] 1.33 SITE READD
- [ ] 1.34 SITE RELOAD
- [ ] 1.35 SITE REMERGE
- [ ] 1.36 SITE RENUSER
- [ ] 1.37 SITE RESCAN
- [ ] 1.38 SITE REQUEST
- [ ] 1.39 SITE REQFILLED
- [ ] 1.40 SITE RULES
- [ ] 1.41 SITE SEEN
- [ ] 1.42 SITE SHUTDOWN
- [ ] 1.43 SITE SLAVE
	 - [ ] 1.43.1 SITE SLAVE addmask
	 - [ ] 1.43.2 SITE SLAVE delmask
	 - [ ] 1.43.3 SITE SLAVE set
- [ ] 1.44 SITE SLAVES
- [ ] 1.45 SITE TAGLINE
- [ ] 1.46 SITE TAKE
- [ ] 1.47 SITE UNBAN
- [ ] 1.48 SITE UNLOADPLUGIN
- [ ] 1.49 SITE UNNUKE
- [ ] 1.50 SITE USER
- [ ] 1.51 SITE USERS
- [ ] 1.52 SITE WHO
- [ ] 1.53 SITE WIPE

**Comment by hgupta9** [comment]
## ProFTPD

[Supported SITE commands](http://proftpd.org/docs/howto/FTP.html)

-  CHGRP
Short for CHange GRouP.

>SITE CHGRP ftpgroup script.cgi

-  CHMOD
Short for CHange MODe.

>SITE CHMOD 755 script.cgi

- HELP

- MKDIR
Similar to the MKD command, this SITE can be used to create a directory. It will, unlike MKD, also create any directories in the path that do not exist.

>SITE MKDIR /path/to/some/dir/that/is/not/there/

Supported by the mod_site_misc module.

-  RMDIR
Similar to the RMD command, this SITE can be used to remove a directory. It will, unlike RMD, also delete any files in the directory.

>SITE RMDIR /path/to/some/dir/with/files/

Supported by the mod_site_misc module.

-  SYMLINK
Used to create a symbolic link (a.k.a. a symlink) from the source path (src) to the destination path (dest).

>SITE SYMLINK src dest

Supported by the mod_site_misc module.

- UTIME
Used to update the access and modification timestamps on a file.

> SITE UTIME 200412312359 /path/to/some/file.txt

Supported by the mod_site_misc module.

**Comment by hgupta9** [comment]
## Pure-FTPd

[SITE commands](https://download.pureftpd.org/pub/pure-ftpd/doc/README)

- SITE IDLE
- SITE CHMOD
- SITE ALIAS - a user can get the list of available aliases

**Comment by hgupta9** [comment]
## IBM OS/400

[SITE commands (page 91)](https://h20566.www2.hpe.com/hpsc/doc/public/display?sp4ts.oid=4201311&docId=emr_na-c02133296&docLocale=en_US)

All useless

- SITE HELP
- SITE CHMOD
- SITE NOCRLF
- SITE SHOWOPEN

**Comment by hgupta9** [comment]
## Windows CE

None supported ([CE 5](https://msdn.microsoft.com/en-us/library/ms884955.aspx), [CE 6](https://msdn.microsoft.com/en-us/library/ee498623(v=winembedded.60).aspx))

**Comment by hgupta9** [comment]
## Vsftpd

[Manpage listing commands](https://security.appspot.com/vsftpd/vsftpd_conf.html)

- SITE CHMOD

**Comment by rharrisxtheta** [comment]
# IBM OS/400

The AS400 has a few 'possibly' useful ones that aren't on this list (the full list is here: https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzaiq/rzaiqpdf.pdf) :

### Commands to do funky and 'probably useful' things 
- RCMD - Run a command on the server using current user's credentials.
- **SITE NAMEFMT / SITE LISTFMT - Get or change format of directory listings and filenames**
    1. **SITE [NAMEFMT|LISTFMT] - Get current filename/listing format**
    2. **SITE [NAMEFMT|LISTFMT] 0 - Use AS400 proprietary format for filenames/directory listings**
    3. **SITE [NAMEFMT|LISTFMT] 1 - Use "unix like" format for filenames / directory listings**
- SITE CRTCCSID - Get/change default CCSID for new files
- SITE NULLFLDS [0|1] - Allow or block transfer of database files that have "nullable" fields.
- SITE TRIM [0|1|2] - Control whether blanks are trimmed from database records

### Commands for working with "Native" AS400 files/libraries/members (since some things like create directory don't work): 
* ADDM - Add physical file member (kind of like 'create file on other OS').
* ADDV - Add variable length member
* CRTL - Create library (kind of like create directory: but supports OS400 'special/main' filesystem)
* CRTP - Create physical file (kind of like 'create table' on SQL, or 'Create File' on other OS)
* CRTS - Create source physical file (similar to CRTP, except works on source files)
* DLTF - Delete file
* DLTL - Delete library 

### Special options for file transfer type (other than ASCII or Binary): 
- B / B[1|2|3|3A|3R|4|4A|4R|5|6|7] - Kanji, ASCII with shift in escape, Korean, Cantonese, etc
- C - Specify a character set ID
- E - Use EBCDIC mode transfer
- F / F1 - EBCDIC Kanji

**Comment by robinrodricks** [comment]
## Serv-U

**RMDA is useful**

[Special commands](https://www.serv-u.com/resources/tutorial/rmda-xrmd-rest-rnfr-rnto-thmb-ftp-command)
[SITE commands](https://support.solarwinds.com/SuccessCenter/s/article/SITE-FTP-command)

- [ ] RMDA
- [ ] THMB
- [ ] SITE EXEC 
- [x] SITE CHMOD - Supported via Chmod() / SetFilePermissions()
- [ ] SITE HELP
- [ ] SITE INDEX
- [ ] SITE MSG
- [ ] SITE PSWD
- [ ] SITE SET
- [ ] SITE ZONE
