### ISSUE TITLE
Source File in EBCDIC - Fluent FTP does not allow the ASCII command WHY?

### ISSUE THREAD

**Issue by Yashuaa** [robinrodricks/FluentFTP#898]
When trying to use `ftpClient.Execute("ASCII")`, a exception is returned saying that "ASCI is not a valid sub command.." 

But is cutting off the extra i in ASCII... what in the world is going on?

The context is 

Trying to FTP a file from a IBM AS/400 to a Windows Machine... Is there anyway to get around this? Otherwise I just get the stupid file in EBCDIC and even know I can convert it to ASCII I lose all of the formatting of the original file...

Please help! @FanDjango @robinrodricks

**Comment by FanDjango** [comment]
Try `ftpClient.Execute("TYPE A")` and also refer to [this](https://www.ibm.com/docs/en/i/7.2?topic=ssw_ibm_i_72/rzaiq/rzaiqtypet.htm).

**Comment by bigbearjeff63** [comment]
On an IBM box you provide the ASCII command once an FTP connection is established to instruct the system you want to download/Upload files in ASCII format. I think the point he's trying to get at is "how can you send the command "ASCII" to the FTP server?" ASCII is a valid command on many IBM boxes when connecting via FTP and that command ensures that the data being pushed/pulled is converted from ASCII to EBCDIC and Vice Versa
![ASCII](https://user-images.githubusercontent.com/35222954/181075947-03d7a48b-ef6a-4ec2-b71e-1e4ad836b38e.JPG)
.

**Comment by FanDjango** [comment]
@bigbearjeff63 

I beg to disagree a little bit. 

> On an IBM box you provide the ASCII command...
> ASCII is a valid command on many IBM boxes

 It is the client that is giving you these options. Of course you use the ASCII (or BINARY) command, but please understand that it is the client that translates this to `TYPE A` or `TYPE B`.

Here you can see the subcommands that the **CLIENT** (the windows FTP command) will accept:

You can see the ASCII, the BINARY and the more powerful TYPE command. ASCII and BINARY are just shortcuts for TYPE xxx

```
C:\WINDOWS\System32>ftp deve
Verbindung mit blabla.blablabla.eu wurde hergestellt.
220-FTPD1 IBM FTP CS V2R4 at blabla.blablabla.eu, 18:11:30 on 2022-07-26.
220 Connection will close if idle for more than 5 minutes.
501 command OPTS aborted -- no options supported for UTF8
Benutzer (blabla.blablabla.eu:(none)): geek
331 Send password please.
Kennwort:
230 GEEK is logged on.  Working directory is "GEEK.".
ftp>
ftp> help
Befehle können abgekürzt werden. Befehle sind:

!               delete          literal         prompt          send
?               debug           ls              put             status
append          dir             mdelete         pwd             trace
ascii           disconnect      mdir            quit            type
bell            get             mget            quote           user
binary          glob            mkdir           recv            verbose
bye             hash            mls             remotehelp
cd              help            mput            rename
close           lcd             open            rmdir
```

If you type `ASCII`, the wonderful Windows FTP Client program will **actually send** `TYPE A`. Turn on a wireshark trace and you see that happening.

To rule out the influence of the different client behaviours on different systems, consider, just for testing, connecting to the control connection of the FTP server by using TELNET, see this example:

**NOTE:** Using telnet is a good trick (can use putty, for example), but since there will be no data connection, you can use it only for trivial stuff, not even a directory listing. It does have the advantage of having **NO** _strange_ influence on the commands you type.

You can see that **HELP** makes no mention of an **ASCII** command.


```
geek@mypc:~# telnet blabla 21
220-FTPD1 IBM FTP CS V2R4 at blabla.blablabla.eu, 18:10:32 on 2022-07-26.
220 Connection will close if idle for more than 5 minutes.
HELP
214-The server-FTP commands are:
214-ABOR,*ACCT,*ALLO, APPE, CDUP,  CWD, DELE, FEAT, HELP, LANG, LIST, MDTM, MKD
214-MODE, NLST, NOOP, OPTS, PASS, PASV, PORT,  PWD, QUIT, REIN, REST, RETR, RMD
214-RNFR, RNTO, SITE, SIZE, *SMNT, SYST, STAT, STOR, STOU, STRU, TYPE, USER
214-ADAT, AUTH, CCC, PBSZ, PROT, EPSV, EPRT
214-The commands preceded by '*' are not implemented
214-The data representation type may be ASCII, EBCDIC or IMAGE, or may be
214-one of the following Double Byte Character Sets:
214-EBCDIC IBM Kanji, Shift JIS Kanji, Extended Unix Code Kanji,
214-JIS 1983 Kanji, JIS 1978 Kanji, Hangeul, Traditional Chinese,
214-or Korean Standard Code KSC-5601, 1989 Version
214-The data structure may be File or Record.
214-The mode may be Stream, Block, or Compressed.
214-If the connection to this server is inactive for more than
214-300 seconds, the connection will be closed.
214-Data set names are represented as either a valid MVS data set name
214-or a valid HFS file name.
214-For information about a particular command, type
214 HELP SERVER command or QUOTE HELP command
HELP TYPE
214-TYPE {representation-type} {format}: the default type is ASCII.
214-The implemented data types are ASCII(TYPE A <N>), EBCDIC (TYPE E <N>),
214-IMAGE (TYPE I), DBCS (TYPE B <options>), and UNICODE (TYPE U 2 <B | L>).
214 The local byte size is 8.
```
Since, with FluentFTP your **client** ist FluentFTP, you are not getting the same "user friendly abbreviations" as you might be getting on other FTP clients. What you send needs to be understood be the server.

**Comment by bigbearjeff63** [comment]
Interesting. That makes a lot better sense. I didn't realize that. Thank you.

**Comment by FanDjango** [comment]
I would like to stress that

`ftpClient.DownloadDataType = FtpDataType.ASCII;`

will cause a transfer to be **preceeded** by the needed `TYPE A` command. No need to do it yourself with an `execute(...`

**Comment by bigbearjeff63** [comment]
So more on this topic. I receive a garbled bunch of unrecognizable text currently. Is this most likely related to a CCSID issue? if so, any idea how to set that value within FluentFTP
![sample](https://user-images.githubusercontent.com/35222954/181087587-0ce4cf39-ecd4-456b-8193-af23011e235d.JPG)
?

**Comment by bigbearjeff63** [comment]
Ignore that last comment. You nailed the nail on the head! that fixed Everything! Thanks so much for your patience and hand holding! =)

**Comment by Yashuaa** [comment]
@FanDjango Thanks so much for your clarity and help.. We were stuck on this for hours!

**Comment by robinrodricks** [comment]
Thanks @FanDjango for getting to this. I was also about to say `ftpClient.DownloadDataType = FtpDataType.ASCII` is the preferred method.

**Comment by FanDjango** [comment]
@robinrodricks this is ibm-zos as well, not only ibm-as400

**Comment by robinrodricks** [comment]
Any change required?
